/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.google.gson.JsonElement;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import one.talon.JSON;

/**
 * Log of application accesses.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class AccessLogEntry {
  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  @javax.annotation.Nonnull
  private String uuid;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private Long status;

  public static final String SERIALIZED_NAME_METHOD = "method";
  @SerializedName(SERIALIZED_NAME_METHOD)
  @javax.annotation.Nonnull
  private String method;

  public static final String SERIALIZED_NAME_REQUEST_URI = "requestUri";
  @SerializedName(SERIALIZED_NAME_REQUEST_URI)
  @javax.annotation.Nonnull
  private String requestUri;

  public static final String SERIALIZED_NAME_TIME = "time";
  @SerializedName(SERIALIZED_NAME_TIME)
  @javax.annotation.Nonnull
  private OffsetDateTime time;

  public static final String SERIALIZED_NAME_REQUEST_PAYLOAD = "requestPayload";
  @SerializedName(SERIALIZED_NAME_REQUEST_PAYLOAD)
  @javax.annotation.Nonnull
  private String requestPayload;

  public static final String SERIALIZED_NAME_RESPONSE_PAYLOAD = "responsePayload";
  @SerializedName(SERIALIZED_NAME_RESPONSE_PAYLOAD)
  @javax.annotation.Nonnull
  private String responsePayload;

  public AccessLogEntry() {
  }

  public AccessLogEntry uuid(@javax.annotation.Nonnull String uuid) {
    this.uuid = uuid;
    return this;
  }

  /**
   * UUID reference of request.
   * @return uuid
   */
  @javax.annotation.Nonnull
  public String getUuid() {
    return uuid;
  }

  public void setUuid(@javax.annotation.Nonnull String uuid) {
    this.uuid = uuid;
  }


  public AccessLogEntry status(@javax.annotation.Nonnull Long status) {
    this.status = status;
    return this;
  }

  /**
   * HTTP status code of response.
   * @return status
   */
  @javax.annotation.Nonnull
  public Long getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull Long status) {
    this.status = status;
  }


  public AccessLogEntry method(@javax.annotation.Nonnull String method) {
    this.method = method;
    return this;
  }

  /**
   * HTTP method of request.
   * @return method
   */
  @javax.annotation.Nonnull
  public String getMethod() {
    return method;
  }

  public void setMethod(@javax.annotation.Nonnull String method) {
    this.method = method;
  }


  public AccessLogEntry requestUri(@javax.annotation.Nonnull String requestUri) {
    this.requestUri = requestUri;
    return this;
  }

  /**
   * target URI of request
   * @return requestUri
   */
  @javax.annotation.Nonnull
  public String getRequestUri() {
    return requestUri;
  }

  public void setRequestUri(@javax.annotation.Nonnull String requestUri) {
    this.requestUri = requestUri;
  }


  public AccessLogEntry time(@javax.annotation.Nonnull OffsetDateTime time) {
    this.time = time;
    return this;
  }

  /**
   * timestamp of request
   * @return time
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getTime() {
    return time;
  }

  public void setTime(@javax.annotation.Nonnull OffsetDateTime time) {
    this.time = time;
  }


  public AccessLogEntry requestPayload(@javax.annotation.Nonnull String requestPayload) {
    this.requestPayload = requestPayload;
    return this;
  }

  /**
   * payload of request
   * @return requestPayload
   */
  @javax.annotation.Nonnull
  public String getRequestPayload() {
    return requestPayload;
  }

  public void setRequestPayload(@javax.annotation.Nonnull String requestPayload) {
    this.requestPayload = requestPayload;
  }


  public AccessLogEntry responsePayload(@javax.annotation.Nonnull String responsePayload) {
    this.responsePayload = responsePayload;
    return this;
  }

  /**
   * payload of response
   * @return responsePayload
   */
  @javax.annotation.Nonnull
  public String getResponsePayload() {
    return responsePayload;
  }

  public void setResponsePayload(@javax.annotation.Nonnull String responsePayload) {
    this.responsePayload = responsePayload;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AccessLogEntry instance itself
   */
  public AccessLogEntry putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessLogEntry accessLogEntry = (AccessLogEntry) o;
    return Objects.equals(this.uuid, accessLogEntry.uuid) &&
        Objects.equals(this.status, accessLogEntry.status) &&
        Objects.equals(this.method, accessLogEntry.method) &&
        Objects.equals(this.requestUri, accessLogEntry.requestUri) &&
        Objects.equals(this.time, accessLogEntry.time) &&
        Objects.equals(this.requestPayload, accessLogEntry.requestPayload) &&
        Objects.equals(this.responsePayload, accessLogEntry.responsePayload)&&
        Objects.equals(this.additionalProperties, accessLogEntry.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, status, method, requestUri, time, requestPayload, responsePayload, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessLogEntry {\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    requestUri: ").append(toIndentedString(requestUri)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    requestPayload: ").append(toIndentedString(requestPayload)).append("\n");
    sb.append("    responsePayload: ").append(toIndentedString(responsePayload)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("uuid", "status", "method", "requestUri", "time", "requestPayload", "responsePayload"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("uuid", "status", "method", "requestUri", "time", "requestPayload", "responsePayload"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AccessLogEntry
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AccessLogEntry.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AccessLogEntry is not found in the empty JSON string", AccessLogEntry.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AccessLogEntry.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("uuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `uuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("uuid").toString()));
      }
      if (!jsonObj.get("method").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `method` to be a primitive type in the JSON string but got `%s`", jsonObj.get("method").toString()));
      }
      if (!jsonObj.get("requestUri").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `requestUri` to be a primitive type in the JSON string but got `%s`", jsonObj.get("requestUri").toString()));
      }
      if (!jsonObj.get("requestPayload").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `requestPayload` to be a primitive type in the JSON string but got `%s`", jsonObj.get("requestPayload").toString()));
      }
      if (!jsonObj.get("responsePayload").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `responsePayload` to be a primitive type in the JSON string but got `%s`", jsonObj.get("responsePayload").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AccessLogEntry.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AccessLogEntry' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AccessLogEntry> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AccessLogEntry.class));

       return (TypeAdapter<T>) new TypeAdapter<AccessLogEntry>() {
           @Override
           public void write(JsonWriter out, AccessLogEntry value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AccessLogEntry read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             AccessLogEntry instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AccessLogEntry given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AccessLogEntry
   * @throws IOException if the JSON string is invalid with respect to AccessLogEntry
   */
  public static AccessLogEntry fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AccessLogEntry.class);
  }

  /**
   * Convert an instance of AccessLogEntry to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

