/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import one.talon.JSON;

/**
 * Account
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class Account {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private Long id;

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  @javax.annotation.Nonnull
  private OffsetDateTime created;

  public static final String SERIALIZED_NAME_MODIFIED = "modified";
  @SerializedName(SERIALIZED_NAME_MODIFIED)
  @javax.annotation.Nonnull
  private OffsetDateTime modified;

  public static final String SERIALIZED_NAME_COMPANY_NAME = "companyName";
  @SerializedName(SERIALIZED_NAME_COMPANY_NAME)
  @javax.annotation.Nonnull
  private String companyName;

  public static final String SERIALIZED_NAME_DOMAIN_NAME = "domainName";
  @SerializedName(SERIALIZED_NAME_DOMAIN_NAME)
  @javax.annotation.Nonnull
  private String domainName;

  /**
   * State of the account (active, deactivated).
   */
  @JsonAdapter(StateEnum.Adapter.class)
  public enum StateEnum {
    ACTIVE("active"),
    
    DEACTIVATED("deactivated");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StateEnum fromValue(String value) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StateEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StateEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StateEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  @javax.annotation.Nonnull
  private StateEnum state;

  public static final String SERIALIZED_NAME_BILLING_EMAIL = "billingEmail";
  @SerializedName(SERIALIZED_NAME_BILLING_EMAIL)
  @javax.annotation.Nonnull
  private String billingEmail;

  public static final String SERIALIZED_NAME_PLAN_NAME = "planName";
  @SerializedName(SERIALIZED_NAME_PLAN_NAME)
  @javax.annotation.Nullable
  private String planName;

  public static final String SERIALIZED_NAME_PLAN_EXPIRES = "planExpires";
  @SerializedName(SERIALIZED_NAME_PLAN_EXPIRES)
  @javax.annotation.Nullable
  private OffsetDateTime planExpires;

  public static final String SERIALIZED_NAME_APPLICATION_LIMIT = "applicationLimit";
  @SerializedName(SERIALIZED_NAME_APPLICATION_LIMIT)
  @javax.annotation.Nullable
  private Long applicationLimit;

  public static final String SERIALIZED_NAME_USER_LIMIT = "userLimit";
  @SerializedName(SERIALIZED_NAME_USER_LIMIT)
  @javax.annotation.Nullable
  private Long userLimit;

  public static final String SERIALIZED_NAME_CAMPAIGN_LIMIT = "campaignLimit";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN_LIMIT)
  @javax.annotation.Nullable
  private Long campaignLimit;

  public static final String SERIALIZED_NAME_API_LIMIT = "apiLimit";
  @SerializedName(SERIALIZED_NAME_API_LIMIT)
  @javax.annotation.Nullable
  private Long apiLimit;

  public static final String SERIALIZED_NAME_APPLICATION_COUNT = "applicationCount";
  @SerializedName(SERIALIZED_NAME_APPLICATION_COUNT)
  @javax.annotation.Nonnull
  private Long applicationCount;

  public static final String SERIALIZED_NAME_USER_COUNT = "userCount";
  @SerializedName(SERIALIZED_NAME_USER_COUNT)
  @javax.annotation.Nonnull
  private Long userCount;

  public static final String SERIALIZED_NAME_CAMPAIGNS_ACTIVE_COUNT = "campaignsActiveCount";
  @SerializedName(SERIALIZED_NAME_CAMPAIGNS_ACTIVE_COUNT)
  @javax.annotation.Nonnull
  private Long campaignsActiveCount;

  public static final String SERIALIZED_NAME_CAMPAIGNS_INACTIVE_COUNT = "campaignsInactiveCount";
  @SerializedName(SERIALIZED_NAME_CAMPAIGNS_INACTIVE_COUNT)
  @javax.annotation.Nonnull
  private Long campaignsInactiveCount;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  @javax.annotation.Nullable
  private Object attributes;

  public Account() {
  }

  public Account id(@javax.annotation.Nonnull Long id) {
    this.id = id;
    return this;
  }

  /**
   * The internal ID of this entity.
   * @return id
   */
  @javax.annotation.Nonnull
  public Long getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull Long id) {
    this.id = id;
  }


  public Account created(@javax.annotation.Nonnull OffsetDateTime created) {
    this.created = created;
    return this;
  }

  /**
   * The time this entity was created.
   * @return created
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(@javax.annotation.Nonnull OffsetDateTime created) {
    this.created = created;
  }


  public Account modified(@javax.annotation.Nonnull OffsetDateTime modified) {
    this.modified = modified;
    return this;
  }

  /**
   * The time this entity was last modified.
   * @return modified
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getModified() {
    return modified;
  }

  public void setModified(@javax.annotation.Nonnull OffsetDateTime modified) {
    this.modified = modified;
  }


  public Account companyName(@javax.annotation.Nonnull String companyName) {
    this.companyName = companyName;
    return this;
  }

  /**
   * Get companyName
   * @return companyName
   */
  @javax.annotation.Nonnull
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(@javax.annotation.Nonnull String companyName) {
    this.companyName = companyName;
  }


  public Account domainName(@javax.annotation.Nonnull String domainName) {
    this.domainName = domainName;
    return this;
  }

  /**
   * Subdomain Name for yourcompany.talon.one.
   * @return domainName
   */
  @javax.annotation.Nonnull
  public String getDomainName() {
    return domainName;
  }

  public void setDomainName(@javax.annotation.Nonnull String domainName) {
    this.domainName = domainName;
  }


  public Account state(@javax.annotation.Nonnull StateEnum state) {
    this.state = state;
    return this;
  }

  /**
   * State of the account (active, deactivated).
   * @return state
   */
  @javax.annotation.Nonnull
  public StateEnum getState() {
    return state;
  }

  public void setState(@javax.annotation.Nonnull StateEnum state) {
    this.state = state;
  }


  public Account billingEmail(@javax.annotation.Nonnull String billingEmail) {
    this.billingEmail = billingEmail;
    return this;
  }

  /**
   * The billing email address associated with your company account.
   * @return billingEmail
   */
  @javax.annotation.Nonnull
  public String getBillingEmail() {
    return billingEmail;
  }

  public void setBillingEmail(@javax.annotation.Nonnull String billingEmail) {
    this.billingEmail = billingEmail;
  }


  public Account planName(@javax.annotation.Nullable String planName) {
    this.planName = planName;
    return this;
  }

  /**
   * The name of your booked plan.
   * @return planName
   */
  @javax.annotation.Nullable
  public String getPlanName() {
    return planName;
  }

  public void setPlanName(@javax.annotation.Nullable String planName) {
    this.planName = planName;
  }


  public Account planExpires(@javax.annotation.Nullable OffsetDateTime planExpires) {
    this.planExpires = planExpires;
    return this;
  }

  /**
   * The point in time at which your current plan expires.
   * @return planExpires
   */
  @javax.annotation.Nullable
  public OffsetDateTime getPlanExpires() {
    return planExpires;
  }

  public void setPlanExpires(@javax.annotation.Nullable OffsetDateTime planExpires) {
    this.planExpires = planExpires;
  }


  public Account applicationLimit(@javax.annotation.Nullable Long applicationLimit) {
    this.applicationLimit = applicationLimit;
    return this;
  }

  /**
   * The maximum number of Applications covered by your plan.
   * @return applicationLimit
   */
  @javax.annotation.Nullable
  public Long getApplicationLimit() {
    return applicationLimit;
  }

  public void setApplicationLimit(@javax.annotation.Nullable Long applicationLimit) {
    this.applicationLimit = applicationLimit;
  }


  public Account userLimit(@javax.annotation.Nullable Long userLimit) {
    this.userLimit = userLimit;
    return this;
  }

  /**
   * The maximum number of Campaign Manager Users covered by your plan.
   * @return userLimit
   */
  @javax.annotation.Nullable
  public Long getUserLimit() {
    return userLimit;
  }

  public void setUserLimit(@javax.annotation.Nullable Long userLimit) {
    this.userLimit = userLimit;
  }


  public Account campaignLimit(@javax.annotation.Nullable Long campaignLimit) {
    this.campaignLimit = campaignLimit;
    return this;
  }

  /**
   * The maximum number of Campaigns covered by your plan.
   * @return campaignLimit
   */
  @javax.annotation.Nullable
  public Long getCampaignLimit() {
    return campaignLimit;
  }

  public void setCampaignLimit(@javax.annotation.Nullable Long campaignLimit) {
    this.campaignLimit = campaignLimit;
  }


  public Account apiLimit(@javax.annotation.Nullable Long apiLimit) {
    this.apiLimit = apiLimit;
    return this;
  }

  /**
   * The maximum number of Integration API calls covered by your plan per billing period.
   * @return apiLimit
   */
  @javax.annotation.Nullable
  public Long getApiLimit() {
    return apiLimit;
  }

  public void setApiLimit(@javax.annotation.Nullable Long apiLimit) {
    this.apiLimit = apiLimit;
  }


  public Account applicationCount(@javax.annotation.Nonnull Long applicationCount) {
    this.applicationCount = applicationCount;
    return this;
  }

  /**
   * The current number of Applications in your account.
   * @return applicationCount
   */
  @javax.annotation.Nonnull
  public Long getApplicationCount() {
    return applicationCount;
  }

  public void setApplicationCount(@javax.annotation.Nonnull Long applicationCount) {
    this.applicationCount = applicationCount;
  }


  public Account userCount(@javax.annotation.Nonnull Long userCount) {
    this.userCount = userCount;
    return this;
  }

  /**
   * The current number of Campaign Manager Users in your account.
   * @return userCount
   */
  @javax.annotation.Nonnull
  public Long getUserCount() {
    return userCount;
  }

  public void setUserCount(@javax.annotation.Nonnull Long userCount) {
    this.userCount = userCount;
  }


  public Account campaignsActiveCount(@javax.annotation.Nonnull Long campaignsActiveCount) {
    this.campaignsActiveCount = campaignsActiveCount;
    return this;
  }

  /**
   * The current number of active Campaigns in your account.
   * @return campaignsActiveCount
   */
  @javax.annotation.Nonnull
  public Long getCampaignsActiveCount() {
    return campaignsActiveCount;
  }

  public void setCampaignsActiveCount(@javax.annotation.Nonnull Long campaignsActiveCount) {
    this.campaignsActiveCount = campaignsActiveCount;
  }


  public Account campaignsInactiveCount(@javax.annotation.Nonnull Long campaignsInactiveCount) {
    this.campaignsInactiveCount = campaignsInactiveCount;
    return this;
  }

  /**
   * The current number of inactive Campaigns in your account.
   * @return campaignsInactiveCount
   */
  @javax.annotation.Nonnull
  public Long getCampaignsInactiveCount() {
    return campaignsInactiveCount;
  }

  public void setCampaignsInactiveCount(@javax.annotation.Nonnull Long campaignsInactiveCount) {
    this.campaignsInactiveCount = campaignsInactiveCount;
  }


  public Account attributes(@javax.annotation.Nullable Object attributes) {
    this.attributes = attributes;
    return this;
  }

  /**
   * Arbitrary properties associated with this campaign.
   * @return attributes
   */
  @javax.annotation.Nullable
  public Object getAttributes() {
    return attributes;
  }

  public void setAttributes(@javax.annotation.Nullable Object attributes) {
    this.attributes = attributes;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Account account = (Account) o;
    return Objects.equals(this.id, account.id) &&
        Objects.equals(this.created, account.created) &&
        Objects.equals(this.modified, account.modified) &&
        Objects.equals(this.companyName, account.companyName) &&
        Objects.equals(this.domainName, account.domainName) &&
        Objects.equals(this.state, account.state) &&
        Objects.equals(this.billingEmail, account.billingEmail) &&
        Objects.equals(this.planName, account.planName) &&
        Objects.equals(this.planExpires, account.planExpires) &&
        Objects.equals(this.applicationLimit, account.applicationLimit) &&
        Objects.equals(this.userLimit, account.userLimit) &&
        Objects.equals(this.campaignLimit, account.campaignLimit) &&
        Objects.equals(this.apiLimit, account.apiLimit) &&
        Objects.equals(this.applicationCount, account.applicationCount) &&
        Objects.equals(this.userCount, account.userCount) &&
        Objects.equals(this.campaignsActiveCount, account.campaignsActiveCount) &&
        Objects.equals(this.campaignsInactiveCount, account.campaignsInactiveCount) &&
        Objects.equals(this.attributes, account.attributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, created, modified, companyName, domainName, state, billingEmail, planName, planExpires, applicationLimit, userLimit, campaignLimit, apiLimit, applicationCount, userCount, campaignsActiveCount, campaignsInactiveCount, attributes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Account {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    domainName: ").append(toIndentedString(domainName)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    billingEmail: ").append(toIndentedString(billingEmail)).append("\n");
    sb.append("    planName: ").append(toIndentedString(planName)).append("\n");
    sb.append("    planExpires: ").append(toIndentedString(planExpires)).append("\n");
    sb.append("    applicationLimit: ").append(toIndentedString(applicationLimit)).append("\n");
    sb.append("    userLimit: ").append(toIndentedString(userLimit)).append("\n");
    sb.append("    campaignLimit: ").append(toIndentedString(campaignLimit)).append("\n");
    sb.append("    apiLimit: ").append(toIndentedString(apiLimit)).append("\n");
    sb.append("    applicationCount: ").append(toIndentedString(applicationCount)).append("\n");
    sb.append("    userCount: ").append(toIndentedString(userCount)).append("\n");
    sb.append("    campaignsActiveCount: ").append(toIndentedString(campaignsActiveCount)).append("\n");
    sb.append("    campaignsInactiveCount: ").append(toIndentedString(campaignsInactiveCount)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "created", "modified", "companyName", "domainName", "state", "billingEmail", "planName", "planExpires", "applicationLimit", "userLimit", "campaignLimit", "apiLimit", "applicationCount", "userCount", "campaignsActiveCount", "campaignsInactiveCount", "attributes"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "created", "modified", "companyName", "domainName", "state", "billingEmail", "applicationCount", "userCount", "campaignsActiveCount", "campaignsInactiveCount"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Account
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Account.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Account is not found in the empty JSON string", Account.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Account.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Account` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Account.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("companyName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `companyName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("companyName").toString()));
      }
      if (!jsonObj.get("domainName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `domainName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("domainName").toString()));
      }
      if (!jsonObj.get("state").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `state` to be a primitive type in the JSON string but got `%s`", jsonObj.get("state").toString()));
      }
      // validate the required field `state`
      StateEnum.validateJsonElement(jsonObj.get("state"));
      if (!jsonObj.get("billingEmail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `billingEmail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("billingEmail").toString()));
      }
      if ((jsonObj.get("planName") != null && !jsonObj.get("planName").isJsonNull()) && !jsonObj.get("planName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `planName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("planName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Account.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Account' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Account> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Account.class));

       return (TypeAdapter<T>) new TypeAdapter<Account>() {
           @Override
           public void write(JsonWriter out, Account value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Account read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Account given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Account
   * @throws IOException if the JSON string is invalid with respect to Account
   */
  public static Account fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Account.class);
  }

  /**
   * Convert an instance of Account to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

