/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import one.talon.model.AttributesSettings;
import one.talon.model.LimitConfig;
import one.talon.model.LoyaltyProgram;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import one.talon.JSON;

/**
 * Application
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class Application {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private Long id;

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  @javax.annotation.Nonnull
  private OffsetDateTime created;

  public static final String SERIALIZED_NAME_MODIFIED = "modified";
  @SerializedName(SERIALIZED_NAME_MODIFIED)
  @javax.annotation.Nonnull
  private OffsetDateTime modified;

  public static final String SERIALIZED_NAME_ACCOUNT_ID = "accountId";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
  @javax.annotation.Nonnull
  private Long accountId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_TIMEZONE = "timezone";
  @SerializedName(SERIALIZED_NAME_TIMEZONE)
  @javax.annotation.Nonnull
  private String timezone;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  @javax.annotation.Nonnull
  private String currency;

  /**
   * The case sensitivity behavior to check coupon codes in the campaigns of this Application.
   */
  @JsonAdapter(CaseSensitivityEnum.Adapter.class)
  public enum CaseSensitivityEnum {
    SENSITIVE("sensitive"),
    
    INSENSITIVE_UPPERCASE("insensitive-uppercase"),
    
    INSENSITIVE_LOWERCASE("insensitive-lowercase");

    private String value;

    CaseSensitivityEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CaseSensitivityEnum fromValue(String value) {
      for (CaseSensitivityEnum b : CaseSensitivityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CaseSensitivityEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CaseSensitivityEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CaseSensitivityEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CaseSensitivityEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      CaseSensitivityEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CASE_SENSITIVITY = "caseSensitivity";
  @SerializedName(SERIALIZED_NAME_CASE_SENSITIVITY)
  @javax.annotation.Nullable
  private CaseSensitivityEnum caseSensitivity;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  @javax.annotation.Nullable
  private Object attributes;

  public static final String SERIALIZED_NAME_LIMITS = "limits";
  @SerializedName(SERIALIZED_NAME_LIMITS)
  @javax.annotation.Nullable
  private List<LimitConfig> limits = new ArrayList<>();

  /**
   * The default scope to apply &#x60;setDiscount&#x60; effects on if no scope was provided with the effect. 
   */
  @JsonAdapter(DefaultDiscountScopeEnum.Adapter.class)
  public enum DefaultDiscountScopeEnum {
    SESSION_TOTAL("sessionTotal"),
    
    CART_ITEMS("cartItems"),
    
    ADDITIONAL_COSTS("additionalCosts");

    private String value;

    DefaultDiscountScopeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DefaultDiscountScopeEnum fromValue(String value) {
      for (DefaultDiscountScopeEnum b : DefaultDiscountScopeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DefaultDiscountScopeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DefaultDiscountScopeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DefaultDiscountScopeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DefaultDiscountScopeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      DefaultDiscountScopeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_DEFAULT_DISCOUNT_SCOPE = "defaultDiscountScope";
  @SerializedName(SERIALIZED_NAME_DEFAULT_DISCOUNT_SCOPE)
  @javax.annotation.Nullable
  private DefaultDiscountScopeEnum defaultDiscountScope;

  public static final String SERIALIZED_NAME_ENABLE_CASCADING_DISCOUNTS = "enableCascadingDiscounts";
  @SerializedName(SERIALIZED_NAME_ENABLE_CASCADING_DISCOUNTS)
  @javax.annotation.Nullable
  private Boolean enableCascadingDiscounts;

  public static final String SERIALIZED_NAME_ENABLE_FLATTENED_CART_ITEMS = "enableFlattenedCartItems";
  @SerializedName(SERIALIZED_NAME_ENABLE_FLATTENED_CART_ITEMS)
  @javax.annotation.Nullable
  private Boolean enableFlattenedCartItems;

  public static final String SERIALIZED_NAME_ATTRIBUTES_SETTINGS = "attributesSettings";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES_SETTINGS)
  @javax.annotation.Nullable
  private AttributesSettings attributesSettings;

  public static final String SERIALIZED_NAME_SANDBOX = "sandbox";
  @SerializedName(SERIALIZED_NAME_SANDBOX)
  @javax.annotation.Nullable
  private Boolean sandbox;

  public static final String SERIALIZED_NAME_ENABLE_PARTIAL_DISCOUNTS = "enablePartialDiscounts";
  @SerializedName(SERIALIZED_NAME_ENABLE_PARTIAL_DISCOUNTS)
  @javax.annotation.Nullable
  private Boolean enablePartialDiscounts;

  /**
   * The default scope to apply &#x60;setDiscountPerItem&#x60; effects on if no scope was provided with the effect. 
   */
  @JsonAdapter(DefaultDiscountAdditionalCostPerItemScopeEnum.Adapter.class)
  public enum DefaultDiscountAdditionalCostPerItemScopeEnum {
    PRICE("price"),
    
    ITEM_TOTAL("itemTotal"),
    
    ADDITIONAL_COSTS("additionalCosts");

    private String value;

    DefaultDiscountAdditionalCostPerItemScopeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DefaultDiscountAdditionalCostPerItemScopeEnum fromValue(String value) {
      for (DefaultDiscountAdditionalCostPerItemScopeEnum b : DefaultDiscountAdditionalCostPerItemScopeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DefaultDiscountAdditionalCostPerItemScopeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DefaultDiscountAdditionalCostPerItemScopeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DefaultDiscountAdditionalCostPerItemScopeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DefaultDiscountAdditionalCostPerItemScopeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      DefaultDiscountAdditionalCostPerItemScopeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_DEFAULT_DISCOUNT_ADDITIONAL_COST_PER_ITEM_SCOPE = "defaultDiscountAdditionalCostPerItemScope";
  @SerializedName(SERIALIZED_NAME_DEFAULT_DISCOUNT_ADDITIONAL_COST_PER_ITEM_SCOPE)
  @javax.annotation.Nullable
  private DefaultDiscountAdditionalCostPerItemScopeEnum defaultDiscountAdditionalCostPerItemScope;

  public static final String SERIALIZED_NAME_DEFAULT_EVALUATION_GROUP_ID = "defaultEvaluationGroupId";
  @SerializedName(SERIALIZED_NAME_DEFAULT_EVALUATION_GROUP_ID)
  @javax.annotation.Nullable
  private Long defaultEvaluationGroupId;

  public static final String SERIALIZED_NAME_DEFAULT_CART_ITEM_FILTER_ID = "defaultCartItemFilterId";
  @SerializedName(SERIALIZED_NAME_DEFAULT_CART_ITEM_FILTER_ID)
  @javax.annotation.Nullable
  private Long defaultCartItemFilterId;

  public static final String SERIALIZED_NAME_ENABLE_CAMPAIGN_STATE_MANAGEMENT = "enableCampaignStateManagement";
  @SerializedName(SERIALIZED_NAME_ENABLE_CAMPAIGN_STATE_MANAGEMENT)
  @javax.annotation.Nullable
  private Boolean enableCampaignStateManagement;

  public static final String SERIALIZED_NAME_LOYALTY_PROGRAMS = "loyaltyPrograms";
  @SerializedName(SERIALIZED_NAME_LOYALTY_PROGRAMS)
  @javax.annotation.Nonnull
  private List<LoyaltyProgram> loyaltyPrograms = new ArrayList<>();

  public Application() {
  }

  public Application id(@javax.annotation.Nonnull Long id) {
    this.id = id;
    return this;
  }

  /**
   * The internal ID of this entity.
   * @return id
   */
  @javax.annotation.Nonnull
  public Long getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull Long id) {
    this.id = id;
  }


  public Application created(@javax.annotation.Nonnull OffsetDateTime created) {
    this.created = created;
    return this;
  }

  /**
   * The time this entity was created.
   * @return created
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(@javax.annotation.Nonnull OffsetDateTime created) {
    this.created = created;
  }


  public Application modified(@javax.annotation.Nonnull OffsetDateTime modified) {
    this.modified = modified;
    return this;
  }

  /**
   * The time this entity was last modified.
   * @return modified
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getModified() {
    return modified;
  }

  public void setModified(@javax.annotation.Nonnull OffsetDateTime modified) {
    this.modified = modified;
  }


  public Application accountId(@javax.annotation.Nonnull Long accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * The ID of the account that owns this entity.
   * @return accountId
   */
  @javax.annotation.Nonnull
  public Long getAccountId() {
    return accountId;
  }

  public void setAccountId(@javax.annotation.Nonnull Long accountId) {
    this.accountId = accountId;
  }


  public Application name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of this application.
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public Application description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * A longer description of the application.
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public Application timezone(@javax.annotation.Nonnull String timezone) {
    this.timezone = timezone;
    return this;
  }

  /**
   * A string containing an IANA timezone descriptor.
   * @return timezone
   */
  @javax.annotation.Nonnull
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(@javax.annotation.Nonnull String timezone) {
    this.timezone = timezone;
  }


  public Application currency(@javax.annotation.Nonnull String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * The default currency for new customer sessions.
   * @return currency
   */
  @javax.annotation.Nonnull
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(@javax.annotation.Nonnull String currency) {
    this.currency = currency;
  }


  public Application caseSensitivity(@javax.annotation.Nullable CaseSensitivityEnum caseSensitivity) {
    this.caseSensitivity = caseSensitivity;
    return this;
  }

  /**
   * The case sensitivity behavior to check coupon codes in the campaigns of this Application.
   * @return caseSensitivity
   */
  @javax.annotation.Nullable
  public CaseSensitivityEnum getCaseSensitivity() {
    return caseSensitivity;
  }

  public void setCaseSensitivity(@javax.annotation.Nullable CaseSensitivityEnum caseSensitivity) {
    this.caseSensitivity = caseSensitivity;
  }


  public Application attributes(@javax.annotation.Nullable Object attributes) {
    this.attributes = attributes;
    return this;
  }

  /**
   * Arbitrary properties associated with this campaign.
   * @return attributes
   */
  @javax.annotation.Nullable
  public Object getAttributes() {
    return attributes;
  }

  public void setAttributes(@javax.annotation.Nullable Object attributes) {
    this.attributes = attributes;
  }


  public Application limits(@javax.annotation.Nullable List<LimitConfig> limits) {
    this.limits = limits;
    return this;
  }

  public Application addLimitsItem(LimitConfig limitsItem) {
    if (this.limits == null) {
      this.limits = new ArrayList<>();
    }
    this.limits.add(limitsItem);
    return this;
  }

  /**
   * Default limits for campaigns created in this application.
   * @return limits
   */
  @javax.annotation.Nullable
  public List<LimitConfig> getLimits() {
    return limits;
  }

  public void setLimits(@javax.annotation.Nullable List<LimitConfig> limits) {
    this.limits = limits;
  }


  public Application defaultDiscountScope(@javax.annotation.Nullable DefaultDiscountScopeEnum defaultDiscountScope) {
    this.defaultDiscountScope = defaultDiscountScope;
    return this;
  }

  /**
   * The default scope to apply &#x60;setDiscount&#x60; effects on if no scope was provided with the effect. 
   * @return defaultDiscountScope
   */
  @javax.annotation.Nullable
  public DefaultDiscountScopeEnum getDefaultDiscountScope() {
    return defaultDiscountScope;
  }

  public void setDefaultDiscountScope(@javax.annotation.Nullable DefaultDiscountScopeEnum defaultDiscountScope) {
    this.defaultDiscountScope = defaultDiscountScope;
  }


  public Application enableCascadingDiscounts(@javax.annotation.Nullable Boolean enableCascadingDiscounts) {
    this.enableCascadingDiscounts = enableCascadingDiscounts;
    return this;
  }

  /**
   * Indicates if discounts should cascade for this Application.
   * @return enableCascadingDiscounts
   */
  @javax.annotation.Nullable
  public Boolean getEnableCascadingDiscounts() {
    return enableCascadingDiscounts;
  }

  public void setEnableCascadingDiscounts(@javax.annotation.Nullable Boolean enableCascadingDiscounts) {
    this.enableCascadingDiscounts = enableCascadingDiscounts;
  }


  public Application enableFlattenedCartItems(@javax.annotation.Nullable Boolean enableFlattenedCartItems) {
    this.enableFlattenedCartItems = enableFlattenedCartItems;
    return this;
  }

  /**
   * Indicates if cart items of quantity larger than one should be separated into different items of quantity one. 
   * @return enableFlattenedCartItems
   */
  @javax.annotation.Nullable
  public Boolean getEnableFlattenedCartItems() {
    return enableFlattenedCartItems;
  }

  public void setEnableFlattenedCartItems(@javax.annotation.Nullable Boolean enableFlattenedCartItems) {
    this.enableFlattenedCartItems = enableFlattenedCartItems;
  }


  public Application attributesSettings(@javax.annotation.Nullable AttributesSettings attributesSettings) {
    this.attributesSettings = attributesSettings;
    return this;
  }

  /**
   * Get attributesSettings
   * @return attributesSettings
   */
  @javax.annotation.Nullable
  public AttributesSettings getAttributesSettings() {
    return attributesSettings;
  }

  public void setAttributesSettings(@javax.annotation.Nullable AttributesSettings attributesSettings) {
    this.attributesSettings = attributesSettings;
  }


  public Application sandbox(@javax.annotation.Nullable Boolean sandbox) {
    this.sandbox = sandbox;
    return this;
  }

  /**
   * Indicates if this is a live or sandbox Application.
   * @return sandbox
   */
  @javax.annotation.Nullable
  public Boolean getSandbox() {
    return sandbox;
  }

  public void setSandbox(@javax.annotation.Nullable Boolean sandbox) {
    this.sandbox = sandbox;
  }


  public Application enablePartialDiscounts(@javax.annotation.Nullable Boolean enablePartialDiscounts) {
    this.enablePartialDiscounts = enablePartialDiscounts;
    return this;
  }

  /**
   * Indicates if this Application supports partial discounts.
   * @return enablePartialDiscounts
   */
  @javax.annotation.Nullable
  public Boolean getEnablePartialDiscounts() {
    return enablePartialDiscounts;
  }

  public void setEnablePartialDiscounts(@javax.annotation.Nullable Boolean enablePartialDiscounts) {
    this.enablePartialDiscounts = enablePartialDiscounts;
  }


  public Application defaultDiscountAdditionalCostPerItemScope(@javax.annotation.Nullable DefaultDiscountAdditionalCostPerItemScopeEnum defaultDiscountAdditionalCostPerItemScope) {
    this.defaultDiscountAdditionalCostPerItemScope = defaultDiscountAdditionalCostPerItemScope;
    return this;
  }

  /**
   * The default scope to apply &#x60;setDiscountPerItem&#x60; effects on if no scope was provided with the effect. 
   * @return defaultDiscountAdditionalCostPerItemScope
   */
  @javax.annotation.Nullable
  public DefaultDiscountAdditionalCostPerItemScopeEnum getDefaultDiscountAdditionalCostPerItemScope() {
    return defaultDiscountAdditionalCostPerItemScope;
  }

  public void setDefaultDiscountAdditionalCostPerItemScope(@javax.annotation.Nullable DefaultDiscountAdditionalCostPerItemScopeEnum defaultDiscountAdditionalCostPerItemScope) {
    this.defaultDiscountAdditionalCostPerItemScope = defaultDiscountAdditionalCostPerItemScope;
  }


  public Application defaultEvaluationGroupId(@javax.annotation.Nullable Long defaultEvaluationGroupId) {
    this.defaultEvaluationGroupId = defaultEvaluationGroupId;
    return this;
  }

  /**
   * The ID of the default campaign evaluation group to which new campaigns will be added unless a different group is selected when creating the campaign.
   * @return defaultEvaluationGroupId
   */
  @javax.annotation.Nullable
  public Long getDefaultEvaluationGroupId() {
    return defaultEvaluationGroupId;
  }

  public void setDefaultEvaluationGroupId(@javax.annotation.Nullable Long defaultEvaluationGroupId) {
    this.defaultEvaluationGroupId = defaultEvaluationGroupId;
  }


  public Application defaultCartItemFilterId(@javax.annotation.Nullable Long defaultCartItemFilterId) {
    this.defaultCartItemFilterId = defaultCartItemFilterId;
    return this;
  }

  /**
   * The ID of the default Cart-Item-Filter for this application.
   * @return defaultCartItemFilterId
   */
  @javax.annotation.Nullable
  public Long getDefaultCartItemFilterId() {
    return defaultCartItemFilterId;
  }

  public void setDefaultCartItemFilterId(@javax.annotation.Nullable Long defaultCartItemFilterId) {
    this.defaultCartItemFilterId = defaultCartItemFilterId;
  }


  public Application enableCampaignStateManagement(@javax.annotation.Nullable Boolean enableCampaignStateManagement) {
    this.enableCampaignStateManagement = enableCampaignStateManagement;
    return this;
  }

  /**
   * Indicates whether the campaign staging and revisions feature is enabled for the Application.  **Important:** After this feature is enabled, it cannot be disabled. 
   * @return enableCampaignStateManagement
   */
  @javax.annotation.Nullable
  public Boolean getEnableCampaignStateManagement() {
    return enableCampaignStateManagement;
  }

  public void setEnableCampaignStateManagement(@javax.annotation.Nullable Boolean enableCampaignStateManagement) {
    this.enableCampaignStateManagement = enableCampaignStateManagement;
  }


  public Application loyaltyPrograms(@javax.annotation.Nonnull List<LoyaltyProgram> loyaltyPrograms) {
    this.loyaltyPrograms = loyaltyPrograms;
    return this;
  }

  public Application addLoyaltyProgramsItem(LoyaltyProgram loyaltyProgramsItem) {
    if (this.loyaltyPrograms == null) {
      this.loyaltyPrograms = new ArrayList<>();
    }
    this.loyaltyPrograms.add(loyaltyProgramsItem);
    return this;
  }

  /**
   * An array containing all the loyalty programs to which this application is subscribed.
   * @return loyaltyPrograms
   */
  @javax.annotation.Nonnull
  public List<LoyaltyProgram> getLoyaltyPrograms() {
    return loyaltyPrograms;
  }

  public void setLoyaltyPrograms(@javax.annotation.Nonnull List<LoyaltyProgram> loyaltyPrograms) {
    this.loyaltyPrograms = loyaltyPrograms;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Application application = (Application) o;
    return Objects.equals(this.id, application.id) &&
        Objects.equals(this.created, application.created) &&
        Objects.equals(this.modified, application.modified) &&
        Objects.equals(this.accountId, application.accountId) &&
        Objects.equals(this.name, application.name) &&
        Objects.equals(this.description, application.description) &&
        Objects.equals(this.timezone, application.timezone) &&
        Objects.equals(this.currency, application.currency) &&
        Objects.equals(this.caseSensitivity, application.caseSensitivity) &&
        Objects.equals(this.attributes, application.attributes) &&
        Objects.equals(this.limits, application.limits) &&
        Objects.equals(this.defaultDiscountScope, application.defaultDiscountScope) &&
        Objects.equals(this.enableCascadingDiscounts, application.enableCascadingDiscounts) &&
        Objects.equals(this.enableFlattenedCartItems, application.enableFlattenedCartItems) &&
        Objects.equals(this.attributesSettings, application.attributesSettings) &&
        Objects.equals(this.sandbox, application.sandbox) &&
        Objects.equals(this.enablePartialDiscounts, application.enablePartialDiscounts) &&
        Objects.equals(this.defaultDiscountAdditionalCostPerItemScope, application.defaultDiscountAdditionalCostPerItemScope) &&
        Objects.equals(this.defaultEvaluationGroupId, application.defaultEvaluationGroupId) &&
        Objects.equals(this.defaultCartItemFilterId, application.defaultCartItemFilterId) &&
        Objects.equals(this.enableCampaignStateManagement, application.enableCampaignStateManagement) &&
        Objects.equals(this.loyaltyPrograms, application.loyaltyPrograms);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, created, modified, accountId, name, description, timezone, currency, caseSensitivity, attributes, limits, defaultDiscountScope, enableCascadingDiscounts, enableFlattenedCartItems, attributesSettings, sandbox, enablePartialDiscounts, defaultDiscountAdditionalCostPerItemScope, defaultEvaluationGroupId, defaultCartItemFilterId, enableCampaignStateManagement, loyaltyPrograms);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Application {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    caseSensitivity: ").append(toIndentedString(caseSensitivity)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    limits: ").append(toIndentedString(limits)).append("\n");
    sb.append("    defaultDiscountScope: ").append(toIndentedString(defaultDiscountScope)).append("\n");
    sb.append("    enableCascadingDiscounts: ").append(toIndentedString(enableCascadingDiscounts)).append("\n");
    sb.append("    enableFlattenedCartItems: ").append(toIndentedString(enableFlattenedCartItems)).append("\n");
    sb.append("    attributesSettings: ").append(toIndentedString(attributesSettings)).append("\n");
    sb.append("    sandbox: ").append(toIndentedString(sandbox)).append("\n");
    sb.append("    enablePartialDiscounts: ").append(toIndentedString(enablePartialDiscounts)).append("\n");
    sb.append("    defaultDiscountAdditionalCostPerItemScope: ").append(toIndentedString(defaultDiscountAdditionalCostPerItemScope)).append("\n");
    sb.append("    defaultEvaluationGroupId: ").append(toIndentedString(defaultEvaluationGroupId)).append("\n");
    sb.append("    defaultCartItemFilterId: ").append(toIndentedString(defaultCartItemFilterId)).append("\n");
    sb.append("    enableCampaignStateManagement: ").append(toIndentedString(enableCampaignStateManagement)).append("\n");
    sb.append("    loyaltyPrograms: ").append(toIndentedString(loyaltyPrograms)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "created", "modified", "accountId", "name", "description", "timezone", "currency", "caseSensitivity", "attributes", "limits", "defaultDiscountScope", "enableCascadingDiscounts", "enableFlattenedCartItems", "attributesSettings", "sandbox", "enablePartialDiscounts", "defaultDiscountAdditionalCostPerItemScope", "defaultEvaluationGroupId", "defaultCartItemFilterId", "enableCampaignStateManagement", "loyaltyPrograms"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "created", "modified", "accountId", "name", "timezone", "currency", "loyaltyPrograms"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Application
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Application.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Application is not found in the empty JSON string", Application.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Application.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Application` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Application.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if (!jsonObj.get("timezone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `timezone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timezone").toString()));
      }
      if (!jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
      if ((jsonObj.get("caseSensitivity") != null && !jsonObj.get("caseSensitivity").isJsonNull()) && !jsonObj.get("caseSensitivity").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `caseSensitivity` to be a primitive type in the JSON string but got `%s`", jsonObj.get("caseSensitivity").toString()));
      }
      // validate the optional field `caseSensitivity`
      if (jsonObj.get("caseSensitivity") != null && !jsonObj.get("caseSensitivity").isJsonNull()) {
        CaseSensitivityEnum.validateJsonElement(jsonObj.get("caseSensitivity"));
      }
      if (jsonObj.get("limits") != null && !jsonObj.get("limits").isJsonNull()) {
        JsonArray jsonArraylimits = jsonObj.getAsJsonArray("limits");
        if (jsonArraylimits != null) {
          // ensure the json data is an array
          if (!jsonObj.get("limits").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `limits` to be an array in the JSON string but got `%s`", jsonObj.get("limits").toString()));
          }

          // validate the optional field `limits` (array)
          for (int i = 0; i < jsonArraylimits.size(); i++) {
            LimitConfig.validateJsonElement(jsonArraylimits.get(i));
          };
        }
      }
      if ((jsonObj.get("defaultDiscountScope") != null && !jsonObj.get("defaultDiscountScope").isJsonNull()) && !jsonObj.get("defaultDiscountScope").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `defaultDiscountScope` to be a primitive type in the JSON string but got `%s`", jsonObj.get("defaultDiscountScope").toString()));
      }
      // validate the optional field `defaultDiscountScope`
      if (jsonObj.get("defaultDiscountScope") != null && !jsonObj.get("defaultDiscountScope").isJsonNull()) {
        DefaultDiscountScopeEnum.validateJsonElement(jsonObj.get("defaultDiscountScope"));
      }
      // validate the optional field `attributesSettings`
      if (jsonObj.get("attributesSettings") != null && !jsonObj.get("attributesSettings").isJsonNull()) {
        AttributesSettings.validateJsonElement(jsonObj.get("attributesSettings"));
      }
      if ((jsonObj.get("defaultDiscountAdditionalCostPerItemScope") != null && !jsonObj.get("defaultDiscountAdditionalCostPerItemScope").isJsonNull()) && !jsonObj.get("defaultDiscountAdditionalCostPerItemScope").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `defaultDiscountAdditionalCostPerItemScope` to be a primitive type in the JSON string but got `%s`", jsonObj.get("defaultDiscountAdditionalCostPerItemScope").toString()));
      }
      // validate the optional field `defaultDiscountAdditionalCostPerItemScope`
      if (jsonObj.get("defaultDiscountAdditionalCostPerItemScope") != null && !jsonObj.get("defaultDiscountAdditionalCostPerItemScope").isJsonNull()) {
        DefaultDiscountAdditionalCostPerItemScopeEnum.validateJsonElement(jsonObj.get("defaultDiscountAdditionalCostPerItemScope"));
      }
      // ensure the json data is an array
      if (!jsonObj.get("loyaltyPrograms").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `loyaltyPrograms` to be an array in the JSON string but got `%s`", jsonObj.get("loyaltyPrograms").toString()));
      }

      JsonArray jsonArrayloyaltyPrograms = jsonObj.getAsJsonArray("loyaltyPrograms");
      // validate the required field `loyaltyPrograms` (array)
      for (int i = 0; i < jsonArrayloyaltyPrograms.size(); i++) {
        LoyaltyProgram.validateJsonElement(jsonArrayloyaltyPrograms.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Application.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Application' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Application> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Application.class));

       return (TypeAdapter<T>) new TypeAdapter<Application>() {
           @Override
           public void write(JsonWriter out, Application value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Application read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Application given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Application
   * @throws IOException if the JSON string is invalid with respect to Application
   */
  public static Application fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Application.class);
  }

  /**
   * Convert an instance of Application to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

