/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import one.talon.model.AwardLoyaltyPointsBlock1Program;
import one.talon.model.AwardLoyaltyPointsBlock1Value;
import one.talon.model.AwardLoyaltyPointsTarget;
import one.talon.model.Block;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import one.talon.JSON;

/**
 * AwardLoyaltyPointsBlock
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class AwardLoyaltyPointsBlock {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private String type;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private List<String> tags;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_PROGRAM = "program";
  @SerializedName(SERIALIZED_NAME_PROGRAM)
  @javax.annotation.Nonnull
  private AwardLoyaltyPointsBlock1Program program;

  /**
   * The customer profile that receives the points. &#x60;Current&#x60; targets the customer in the current session; &#x60;Advocate&#x60; targets the person who invited their friend via referral program.
   */
  @JsonAdapter(RecipientEnum.Adapter.class)
  public enum RecipientEnum {
    CURRENT("Current"),
    
    ADVOCATE("Advocate");

    private String value;

    RecipientEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static RecipientEnum fromValue(String value) {
      for (RecipientEnum b : RecipientEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<RecipientEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RecipientEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RecipientEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return RecipientEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      RecipientEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_RECIPIENT = "recipient";
  @SerializedName(SERIALIZED_NAME_RECIPIENT)
  @javax.annotation.Nonnull
  private RecipientEnum recipient;

  public static final String SERIALIZED_NAME_SUBLEDGER = "subledger";
  @SerializedName(SERIALIZED_NAME_SUBLEDGER)
  @javax.annotation.Nonnull
  private String subledger;

  public static final String SERIALIZED_NAME_TARGET = "target";
  @SerializedName(SERIALIZED_NAME_TARGET)
  @javax.annotation.Nonnull
  private AwardLoyaltyPointsTarget target;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  @javax.annotation.Nonnull
  private AwardLoyaltyPointsBlock1Value value;

  public static final String SERIALIZED_NAME_PARTIAL = "partial";
  @SerializedName(SERIALIZED_NAME_PARTIAL)
  @javax.annotation.Nullable
  private Boolean partial;

  public static final String SERIALIZED_NAME_AWAITS_ACTIVATION = "awaitsActivation";
  @SerializedName(SERIALIZED_NAME_AWAITS_ACTIVATION)
  @javax.annotation.Nullable
  private Boolean awaitsActivation;

  public static final String SERIALIZED_NAME_START_DATE = "startDate";
  @SerializedName(SERIALIZED_NAME_START_DATE)
  @javax.annotation.Nullable
  private Object startDate = null;

  public static final String SERIALIZED_NAME_VALIDITY_DURATION = "validityDuration";
  @SerializedName(SERIALIZED_NAME_VALIDITY_DURATION)
  @javax.annotation.Nullable
  private String validityDuration;

  public static final String SERIALIZED_NAME_EXPIRY_DATE = "expiryDate";
  @SerializedName(SERIALIZED_NAME_EXPIRY_DATE)
  @javax.annotation.Nullable
  private Object expiryDate = null;

  public static final String SERIALIZED_NAME_PENDING_DURATION = "pendingDuration";
  @SerializedName(SERIALIZED_NAME_PENDING_DURATION)
  @javax.annotation.Nullable
  private String pendingDuration;

  public static final String SERIALIZED_NAME_ON_FAILURE = "onFailure";
  @SerializedName(SERIALIZED_NAME_ON_FAILURE)
  @javax.annotation.Nullable
  private List<Block> onFailure;

  public AwardLoyaltyPointsBlock() {
  }

  public AwardLoyaltyPointsBlock(
     String id, 
     List<String> tags
  ) {
    this();
    this.id = id;
    this.tags = tags;
  }

  /**
   * Unique identifier for this block.
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }



  public AwardLoyaltyPointsBlock type(@javax.annotation.Nonnull String type) {
    this.type = type;
    return this;
  }

  /**
   * Identifies the block variant and determines which additional properties are present in it.
   * @return type
   */
  @javax.annotation.Nonnull
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull String type) {
    this.type = type;
  }


  /**
   * Semantic labels attached to this block.
   * @return tags
   */
  @javax.annotation.Nullable
  public List<String> getTags() {
    return tags;
  }



  public AwardLoyaltyPointsBlock name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The human-readable label attached to the awarded points.
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public AwardLoyaltyPointsBlock program(@javax.annotation.Nonnull AwardLoyaltyPointsBlock1Program program) {
    this.program = program;
    return this;
  }

  /**
   * Get program
   * @return program
   */
  @javax.annotation.Nonnull
  public AwardLoyaltyPointsBlock1Program getProgram() {
    return program;
  }

  public void setProgram(@javax.annotation.Nonnull AwardLoyaltyPointsBlock1Program program) {
    this.program = program;
  }


  public AwardLoyaltyPointsBlock recipient(@javax.annotation.Nonnull RecipientEnum recipient) {
    this.recipient = recipient;
    return this;
  }

  /**
   * The customer profile that receives the points. &#x60;Current&#x60; targets the customer in the current session; &#x60;Advocate&#x60; targets the person who invited their friend via referral program.
   * @return recipient
   */
  @javax.annotation.Nonnull
  public RecipientEnum getRecipient() {
    return recipient;
  }

  public void setRecipient(@javax.annotation.Nonnull RecipientEnum recipient) {
    this.recipient = recipient;
  }


  public AwardLoyaltyPointsBlock subledger(@javax.annotation.Nonnull String subledger) {
    this.subledger = subledger;
    return this;
  }

  /**
   * The name of the subledger to add points to. Can be empty if this block adds points to the loyalty program&#39;s main ledger instead of a subledger.
   * @return subledger
   */
  @javax.annotation.Nonnull
  public String getSubledger() {
    return subledger;
  }

  public void setSubledger(@javax.annotation.Nonnull String subledger) {
    this.subledger = subledger;
  }


  public AwardLoyaltyPointsBlock target(@javax.annotation.Nonnull AwardLoyaltyPointsTarget target) {
    this.target = target;
    return this;
  }

  /**
   * Get target
   * @return target
   */
  @javax.annotation.Nonnull
  public AwardLoyaltyPointsTarget getTarget() {
    return target;
  }

  public void setTarget(@javax.annotation.Nonnull AwardLoyaltyPointsTarget target) {
    this.target = target;
  }


  public AwardLoyaltyPointsBlock value(@javax.annotation.Nonnull AwardLoyaltyPointsBlock1Value value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @javax.annotation.Nonnull
  public AwardLoyaltyPointsBlock1Value getValue() {
    return value;
  }

  public void setValue(@javax.annotation.Nonnull AwardLoyaltyPointsBlock1Value value) {
    this.value = value;
  }


  public AwardLoyaltyPointsBlock partial(@javax.annotation.Nullable Boolean partial) {
    this.partial = partial;
    return this;
  }

  /**
   * When &#x60;true&#x60;, applies a partial points reward when the requested value exceeds the configured budget.
   * @return partial
   */
  @javax.annotation.Nullable
  public Boolean getPartial() {
    return partial;
  }

  public void setPartial(@javax.annotation.Nullable Boolean partial) {
    this.partial = partial;
  }


  public AwardLoyaltyPointsBlock awaitsActivation(@javax.annotation.Nullable Boolean awaitsActivation) {
    this.awaitsActivation = awaitsActivation;
    return this;
  }

  /**
   * When &#x60;true&#x60;, the awarded points require manual or delayed activation before becoming active. Mutually exclusive with &#x60;startDate&#x60;.
   * @return awaitsActivation
   */
  @javax.annotation.Nullable
  public Boolean getAwaitsActivation() {
    return awaitsActivation;
  }

  public void setAwaitsActivation(@javax.annotation.Nullable Boolean awaitsActivation) {
    this.awaitsActivation = awaitsActivation;
  }


  public AwardLoyaltyPointsBlock startDate(@javax.annotation.Nullable Object startDate) {
    this.startDate = startDate;
    return this;
  }

  /**
   * Timestamp at which the awarded points become active. Mutually exclusive with &#x60;awaitsActivation&#x60;.
   * @return startDate
   */
  @javax.annotation.Nullable
  public Object getStartDate() {
    return startDate;
  }

  public void setStartDate(@javax.annotation.Nullable Object startDate) {
    this.startDate = startDate;
  }


  public AwardLoyaltyPointsBlock validityDuration(@javax.annotation.Nullable String validityDuration) {
    this.validityDuration = validityDuration;
    return this;
  }

  /**
   * Relative duration (e.g. &#x60;30D&#x60;) after which the awarded points expire. Mutually exclusive with &#x60;expiryDate&#x60;.
   * @return validityDuration
   */
  @javax.annotation.Nullable
  public String getValidityDuration() {
    return validityDuration;
  }

  public void setValidityDuration(@javax.annotation.Nullable String validityDuration) {
    this.validityDuration = validityDuration;
  }


  public AwardLoyaltyPointsBlock expiryDate(@javax.annotation.Nullable Object expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

  /**
   * Timestamp at which the awarded points expire. Mutually exclusive with &#x60;validityDuration&#x60;.
   * @return expiryDate
   */
  @javax.annotation.Nullable
  public Object getExpiryDate() {
    return expiryDate;
  }

  public void setExpiryDate(@javax.annotation.Nullable Object expiryDate) {
    this.expiryDate = expiryDate;
  }


  public AwardLoyaltyPointsBlock pendingDuration(@javax.annotation.Nullable String pendingDuration) {
    this.pendingDuration = pendingDuration;
    return this;
  }

  /**
   * Relative duration (e.g. &#x60;3D&#x60;) the awarded points remain pending before activation.
   * @return pendingDuration
   */
  @javax.annotation.Nullable
  public String getPendingDuration() {
    return pendingDuration;
  }

  public void setPendingDuration(@javax.annotation.Nullable String pendingDuration) {
    this.pendingDuration = pendingDuration;
  }


  public AwardLoyaltyPointsBlock onFailure(@javax.annotation.Nullable List<Block> onFailure) {
    this.onFailure = onFailure;
    return this;
  }

  public AwardLoyaltyPointsBlock addOnFailureItem(Block onFailureItem) {
    if (this.onFailure == null) {
      this.onFailure = new ArrayList<>();
    }
    this.onFailure.add(onFailureItem);
    return this;
  }

  /**
   * Promotion blocks evaluated when this block fails or returns false.
   * @return onFailure
   */
  @javax.annotation.Nullable
  public List<Block> getOnFailure() {
    return onFailure;
  }

  public void setOnFailure(@javax.annotation.Nullable List<Block> onFailure) {
    this.onFailure = onFailure;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AwardLoyaltyPointsBlock instance itself
   */
  public AwardLoyaltyPointsBlock putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AwardLoyaltyPointsBlock awardLoyaltyPointsBlock = (AwardLoyaltyPointsBlock) o;
    return Objects.equals(this.id, awardLoyaltyPointsBlock.id) &&
        Objects.equals(this.type, awardLoyaltyPointsBlock.type) &&
        Objects.equals(this.tags, awardLoyaltyPointsBlock.tags) &&
        Objects.equals(this.name, awardLoyaltyPointsBlock.name) &&
        Objects.equals(this.program, awardLoyaltyPointsBlock.program) &&
        Objects.equals(this.recipient, awardLoyaltyPointsBlock.recipient) &&
        Objects.equals(this.subledger, awardLoyaltyPointsBlock.subledger) &&
        Objects.equals(this.target, awardLoyaltyPointsBlock.target) &&
        Objects.equals(this.value, awardLoyaltyPointsBlock.value) &&
        Objects.equals(this.partial, awardLoyaltyPointsBlock.partial) &&
        Objects.equals(this.awaitsActivation, awardLoyaltyPointsBlock.awaitsActivation) &&
        Objects.equals(this.startDate, awardLoyaltyPointsBlock.startDate) &&
        Objects.equals(this.validityDuration, awardLoyaltyPointsBlock.validityDuration) &&
        Objects.equals(this.expiryDate, awardLoyaltyPointsBlock.expiryDate) &&
        Objects.equals(this.pendingDuration, awardLoyaltyPointsBlock.pendingDuration) &&
        Objects.equals(this.onFailure, awardLoyaltyPointsBlock.onFailure)&&
        Objects.equals(this.additionalProperties, awardLoyaltyPointsBlock.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, tags, name, program, recipient, subledger, target, value, partial, awaitsActivation, startDate, validityDuration, expiryDate, pendingDuration, onFailure, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AwardLoyaltyPointsBlock {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    program: ").append(toIndentedString(program)).append("\n");
    sb.append("    recipient: ").append(toIndentedString(recipient)).append("\n");
    sb.append("    subledger: ").append(toIndentedString(subledger)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    partial: ").append(toIndentedString(partial)).append("\n");
    sb.append("    awaitsActivation: ").append(toIndentedString(awaitsActivation)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    validityDuration: ").append(toIndentedString(validityDuration)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    pendingDuration: ").append(toIndentedString(pendingDuration)).append("\n");
    sb.append("    onFailure: ").append(toIndentedString(onFailure)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "type", "tags", "name", "program", "recipient", "subledger", "target", "value", "partial", "awaitsActivation", "startDate", "validityDuration", "expiryDate", "pendingDuration", "onFailure"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("type", "name", "program", "recipient", "subledger", "target", "value"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AwardLoyaltyPointsBlock
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AwardLoyaltyPointsBlock.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AwardLoyaltyPointsBlock is not found in the empty JSON string", AwardLoyaltyPointsBlock.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AwardLoyaltyPointsBlock.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonNull() && !jsonObj.get("tags").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // validate the required field `program`
      AwardLoyaltyPointsBlock1Program.validateJsonElement(jsonObj.get("program"));
      if (!jsonObj.get("recipient").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `recipient` to be a primitive type in the JSON string but got `%s`", jsonObj.get("recipient").toString()));
      }
      // validate the required field `recipient`
      RecipientEnum.validateJsonElement(jsonObj.get("recipient"));
      if (!jsonObj.get("subledger").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `subledger` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subledger").toString()));
      }
      // validate the required field `target`
      AwardLoyaltyPointsTarget.validateJsonElement(jsonObj.get("target"));
      // validate the required field `value`
      AwardLoyaltyPointsBlock1Value.validateJsonElement(jsonObj.get("value"));
      if ((jsonObj.get("validityDuration") != null && !jsonObj.get("validityDuration").isJsonNull()) && !jsonObj.get("validityDuration").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `validityDuration` to be a primitive type in the JSON string but got `%s`", jsonObj.get("validityDuration").toString()));
      }
      if ((jsonObj.get("pendingDuration") != null && !jsonObj.get("pendingDuration").isJsonNull()) && !jsonObj.get("pendingDuration").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `pendingDuration` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pendingDuration").toString()));
      }
      if (jsonObj.get("onFailure") != null && !jsonObj.get("onFailure").isJsonNull()) {
        JsonArray jsonArrayonFailure = jsonObj.getAsJsonArray("onFailure");
        if (jsonArrayonFailure != null) {
          // ensure the json data is an array
          if (!jsonObj.get("onFailure").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `onFailure` to be an array in the JSON string but got `%s`", jsonObj.get("onFailure").toString()));
          }

          // validate the optional field `onFailure` (array)
          for (int i = 0; i < jsonArrayonFailure.size(); i++) {
            Block.validateJsonElement(jsonArrayonFailure.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AwardLoyaltyPointsBlock.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AwardLoyaltyPointsBlock' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AwardLoyaltyPointsBlock> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AwardLoyaltyPointsBlock.class));

       return (TypeAdapter<T>) new TypeAdapter<AwardLoyaltyPointsBlock>() {
           @Override
           public void write(JsonWriter out, AwardLoyaltyPointsBlock value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonNull()) {
                     obj.add(entry.getKey(), JsonNull.INSTANCE);
                   } else if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AwardLoyaltyPointsBlock read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             AwardLoyaltyPointsBlock instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AwardLoyaltyPointsBlock given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AwardLoyaltyPointsBlock
   * @throws IOException if the JSON string is invalid with respect to AwardLoyaltyPointsBlock
   */
  public static AwardLoyaltyPointsBlock fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AwardLoyaltyPointsBlock.class);
  }

  /**
   * Convert an instance of AwardLoyaltyPointsBlock to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

