/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import one.talon.model.BestPriorPriceMetadata;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import one.talon.JSON;

/**
 * BestPriorPrice
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class BestPriorPrice {
  public static final String SERIALIZED_NAME_SKU = "sku";
  @SerializedName(SERIALIZED_NAME_SKU)
  @javax.annotation.Nonnull
  private String sku;

  public static final String SERIALIZED_NAME_OBSERVED_AT = "observedAt";
  @SerializedName(SERIALIZED_NAME_OBSERVED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime observedAt;

  public static final String SERIALIZED_NAME_CONTEXT_ID = "contextId";
  @SerializedName(SERIALIZED_NAME_CONTEXT_ID)
  @javax.annotation.Nonnull
  private String contextId;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  @javax.annotation.Nonnull
  private BigDecimal price;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  @javax.annotation.Nonnull
  private BestPriorPriceMetadata metadata;

  public static final String SERIALIZED_NAME_TARGET = "target";
  @SerializedName(SERIALIZED_NAME_TARGET)
  @javax.annotation.Nonnull
  private Object target;

  public BestPriorPrice() {
  }

  public BestPriorPrice sku(@javax.annotation.Nonnull String sku) {
    this.sku = sku;
    return this;
  }

  /**
   * sku
   * @return sku
   */
  @javax.annotation.Nonnull
  public String getSku() {
    return sku;
  }

  public void setSku(@javax.annotation.Nonnull String sku) {
    this.sku = sku;
  }


  public BestPriorPrice observedAt(@javax.annotation.Nonnull OffsetDateTime observedAt) {
    this.observedAt = observedAt;
    return this;
  }

  /**
   * The date and time when the best price was observed.
   * @return observedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getObservedAt() {
    return observedAt;
  }

  public void setObservedAt(@javax.annotation.Nonnull OffsetDateTime observedAt) {
    this.observedAt = observedAt;
  }


  public BestPriorPrice contextId(@javax.annotation.Nonnull String contextId) {
    this.contextId = contextId;
    return this;
  }

  /**
   * The context ID of the context active at the time of observation. 
   * @return contextId
   */
  @javax.annotation.Nonnull
  public String getContextId() {
    return contextId;
  }

  public void setContextId(@javax.annotation.Nonnull String contextId) {
    this.contextId = contextId;
  }


  public BestPriorPrice price(@javax.annotation.Nonnull BigDecimal price) {
    this.price = price;
    return this;
  }

  /**
   * Price of the item.
   * @return price
   */
  @javax.annotation.Nonnull
  public BigDecimal getPrice() {
    return price;
  }

  public void setPrice(@javax.annotation.Nonnull BigDecimal price) {
    this.price = price;
  }


  public BestPriorPrice metadata(@javax.annotation.Nonnull BestPriorPriceMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nonnull
  public BestPriorPriceMetadata getMetadata() {
    return metadata;
  }

  public void setMetadata(@javax.annotation.Nonnull BestPriorPriceMetadata metadata) {
    this.metadata = metadata;
  }


  public BestPriorPrice target(@javax.annotation.Nonnull Object target) {
    this.target = target;
    return this;
  }

  /**
   * Get target
   * @return target
   */
  @javax.annotation.Nonnull
  public Object getTarget() {
    return target;
  }

  public void setTarget(@javax.annotation.Nonnull Object target) {
    this.target = target;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BestPriorPrice bestPriorPrice = (BestPriorPrice) o;
    return Objects.equals(this.sku, bestPriorPrice.sku) &&
        Objects.equals(this.observedAt, bestPriorPrice.observedAt) &&
        Objects.equals(this.contextId, bestPriorPrice.contextId) &&
        Objects.equals(this.price, bestPriorPrice.price) &&
        Objects.equals(this.metadata, bestPriorPrice.metadata) &&
        Objects.equals(this.target, bestPriorPrice.target);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sku, observedAt, contextId, price, metadata, target);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BestPriorPrice {\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    observedAt: ").append(toIndentedString(observedAt)).append("\n");
    sb.append("    contextId: ").append(toIndentedString(contextId)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("sku", "observedAt", "contextId", "price", "metadata", "target"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("sku", "observedAt", "contextId", "price", "metadata", "target"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BestPriorPrice
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BestPriorPrice.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in BestPriorPrice is not found in the empty JSON string", BestPriorPrice.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BestPriorPrice.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `BestPriorPrice` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BestPriorPrice.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("sku").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sku` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sku").toString()));
      }
      if (!jsonObj.get("contextId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `contextId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contextId").toString()));
      }
      // validate the required field `metadata`
      BestPriorPriceMetadata.validateJsonElement(jsonObj.get("metadata"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BestPriorPrice.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BestPriorPrice' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BestPriorPrice> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BestPriorPrice.class));

       return (TypeAdapter<T>) new TypeAdapter<BestPriorPrice>() {
           @Override
           public void write(JsonWriter out, BestPriorPrice value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BestPriorPrice read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BestPriorPrice given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BestPriorPrice
   * @throws IOException if the JSON string is invalid with respect to BestPriorPrice
   */
  public static BestPriorPrice fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BestPriorPrice.class);
  }

  /**
   * Convert an instance of BestPriorPrice to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

