/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import one.talon.model.Campaign;
import one.talon.model.CampaignEvaluationPosition;
import one.talon.model.Ruleset;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import one.talon.JSON;

/**
 * CampaignCreatedNotificationItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class CampaignCreatedNotificationItem {
  public static final String SERIALIZED_NAME_EVENT = "Event";
  @SerializedName(SERIALIZED_NAME_EVENT)
  @javax.annotation.Nonnull
  private String event;

  public static final String SERIALIZED_NAME_CAMPAIGN = "campaign";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN)
  @javax.annotation.Nonnull
  private Campaign campaign;

  public static final String SERIALIZED_NAME_RULESET = "ruleset";
  @SerializedName(SERIALIZED_NAME_RULESET)
  @javax.annotation.Nullable
  private Ruleset ruleset;

  public static final String SERIALIZED_NAME_EVALUATION_POSITION = "evaluationPosition";
  @SerializedName(SERIALIZED_NAME_EVALUATION_POSITION)
  @javax.annotation.Nonnull
  private CampaignEvaluationPosition evaluationPosition;

  public CampaignCreatedNotificationItem() {
  }

  public CampaignCreatedNotificationItem event(@javax.annotation.Nonnull String event) {
    this.event = event;
    return this;
  }

  /**
   * The type of the event. Can be one of the following: [&#39;campaign_state_changed&#39;, &#39;campaign_ruleset_changed&#39;, &#39;campaign_edited&#39;, &#39;campaign_created&#39;, &#39;campaign_deleted&#39;] 
   * @return event
   */
  @javax.annotation.Nonnull
  public String getEvent() {
    return event;
  }

  public void setEvent(@javax.annotation.Nonnull String event) {
    this.event = event;
  }


  public CampaignCreatedNotificationItem campaign(@javax.annotation.Nonnull Campaign campaign) {
    this.campaign = campaign;
    return this;
  }

  /**
   * The campaign whose state changed.
   * @return campaign
   */
  @javax.annotation.Nonnull
  public Campaign getCampaign() {
    return campaign;
  }

  public void setCampaign(@javax.annotation.Nonnull Campaign campaign) {
    this.campaign = campaign;
  }


  public CampaignCreatedNotificationItem ruleset(@javax.annotation.Nullable Ruleset ruleset) {
    this.ruleset = ruleset;
    return this;
  }

  /**
   * The current ruleset.
   * @return ruleset
   */
  @javax.annotation.Nullable
  public Ruleset getRuleset() {
    return ruleset;
  }

  public void setRuleset(@javax.annotation.Nullable Ruleset ruleset) {
    this.ruleset = ruleset;
  }


  public CampaignCreatedNotificationItem evaluationPosition(@javax.annotation.Nonnull CampaignEvaluationPosition evaluationPosition) {
    this.evaluationPosition = evaluationPosition;
    return this;
  }

  /**
   * The campaign position within the evaluation tree.
   * @return evaluationPosition
   */
  @javax.annotation.Nonnull
  public CampaignEvaluationPosition getEvaluationPosition() {
    return evaluationPosition;
  }

  public void setEvaluationPosition(@javax.annotation.Nonnull CampaignEvaluationPosition evaluationPosition) {
    this.evaluationPosition = evaluationPosition;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CampaignCreatedNotificationItem campaignCreatedNotificationItem = (CampaignCreatedNotificationItem) o;
    return Objects.equals(this.event, campaignCreatedNotificationItem.event) &&
        Objects.equals(this.campaign, campaignCreatedNotificationItem.campaign) &&
        Objects.equals(this.ruleset, campaignCreatedNotificationItem.ruleset) &&
        Objects.equals(this.evaluationPosition, campaignCreatedNotificationItem.evaluationPosition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(event, campaign, ruleset, evaluationPosition);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CampaignCreatedNotificationItem {\n");
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    campaign: ").append(toIndentedString(campaign)).append("\n");
    sb.append("    ruleset: ").append(toIndentedString(ruleset)).append("\n");
    sb.append("    evaluationPosition: ").append(toIndentedString(evaluationPosition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("Event", "campaign", "ruleset", "evaluationPosition"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("Event", "campaign", "evaluationPosition"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CampaignCreatedNotificationItem
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CampaignCreatedNotificationItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in CampaignCreatedNotificationItem is not found in the empty JSON string", CampaignCreatedNotificationItem.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CampaignCreatedNotificationItem.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CampaignCreatedNotificationItem` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CampaignCreatedNotificationItem.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("Event").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `Event` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Event").toString()));
      }
      // validate the required field `campaign`
      Campaign.validateJsonElement(jsonObj.get("campaign"));
      // validate the optional field `ruleset`
      if (jsonObj.get("ruleset") != null && !jsonObj.get("ruleset").isJsonNull()) {
        Ruleset.validateJsonElement(jsonObj.get("ruleset"));
      }
      // validate the required field `evaluationPosition`
      CampaignEvaluationPosition.validateJsonElement(jsonObj.get("evaluationPosition"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CampaignCreatedNotificationItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CampaignCreatedNotificationItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CampaignCreatedNotificationItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CampaignCreatedNotificationItem.class));

       return (TypeAdapter<T>) new TypeAdapter<CampaignCreatedNotificationItem>() {
           @Override
           public void write(JsonWriter out, CampaignCreatedNotificationItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CampaignCreatedNotificationItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CampaignCreatedNotificationItem given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CampaignCreatedNotificationItem
   * @throws IOException if the JSON string is invalid with respect to CampaignCreatedNotificationItem
   */
  public static CampaignCreatedNotificationItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CampaignCreatedNotificationItem.class);
  }

  /**
   * Convert an instance of CampaignCreatedNotificationItem to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

