/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import one.talon.model.ExtendedCoupon;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import one.talon.JSON;

/**
 * CouponsNotificationData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0-SNAPSHOT")
public class CouponsNotificationData {
  public static final String SERIALIZED_NAME_TYPE_OF_CHANGE = "TypeOfChange";
  @SerializedName(SERIALIZED_NAME_TYPE_OF_CHANGE)
  @javax.annotation.Nonnull
  private String typeOfChange;

  public static final String SERIALIZED_NAME_OPERATION = "Operation";
  @SerializedName(SERIALIZED_NAME_OPERATION)
  @javax.annotation.Nonnull
  private String operation;

  public static final String SERIALIZED_NAME_EMPLOYEE_NAME = "EmployeeName";
  @SerializedName(SERIALIZED_NAME_EMPLOYEE_NAME)
  @javax.annotation.Nonnull
  private String employeeName;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  @javax.annotation.Nullable
  private List<ExtendedCoupon> data = new ArrayList<>();

  public static final String SERIALIZED_NAME_TOTAL_RESULT_SIZE = "totalResultSize";
  @SerializedName(SERIALIZED_NAME_TOTAL_RESULT_SIZE)
  @javax.annotation.Nullable
  private Long totalResultSize;

  public static final String SERIALIZED_NAME_NOTIFICATION_TYPE = "NotificationType";
  @SerializedName(SERIALIZED_NAME_NOTIFICATION_TYPE)
  @javax.annotation.Nonnull
  private String notificationType;

  public CouponsNotificationData() {
  }

  public CouponsNotificationData typeOfChange(@javax.annotation.Nonnull String typeOfChange) {
    this.typeOfChange = typeOfChange;
    return this;
  }

  /**
   * The type of change that occurred.
   * @return typeOfChange
   */
  @javax.annotation.Nonnull
  public String getTypeOfChange() {
    return typeOfChange;
  }

  public void setTypeOfChange(@javax.annotation.Nonnull String typeOfChange) {
    this.typeOfChange = typeOfChange;
  }


  public CouponsNotificationData operation(@javax.annotation.Nonnull String operation) {
    this.operation = operation;
    return this;
  }

  /**
   * The operation performed.
   * @return operation
   */
  @javax.annotation.Nonnull
  public String getOperation() {
    return operation;
  }

  public void setOperation(@javax.annotation.Nonnull String operation) {
    this.operation = operation;
  }


  public CouponsNotificationData employeeName(@javax.annotation.Nonnull String employeeName) {
    this.employeeName = employeeName;
    return this;
  }

  /**
   * The name of the employee associated with the operation.
   * @return employeeName
   */
  @javax.annotation.Nonnull
  public String getEmployeeName() {
    return employeeName;
  }

  public void setEmployeeName(@javax.annotation.Nonnull String employeeName) {
    this.employeeName = employeeName;
  }


  public CouponsNotificationData data(@javax.annotation.Nullable List<ExtendedCoupon> data) {
    this.data = data;
    return this;
  }

  public CouponsNotificationData addDataItem(ExtendedCoupon dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * A list of extended coupon data.
   * @return data
   */
  @javax.annotation.Nullable
  public List<ExtendedCoupon> getData() {
    return data;
  }

  public void setData(@javax.annotation.Nullable List<ExtendedCoupon> data) {
    this.data = data;
  }


  public CouponsNotificationData totalResultSize(@javax.annotation.Nullable Long totalResultSize) {
    this.totalResultSize = totalResultSize;
    return this;
  }

  /**
   * Get totalResultSize
   * @return totalResultSize
   */
  @javax.annotation.Nullable
  public Long getTotalResultSize() {
    return totalResultSize;
  }

  public void setTotalResultSize(@javax.annotation.Nullable Long totalResultSize) {
    this.totalResultSize = totalResultSize;
  }


  public CouponsNotificationData notificationType(@javax.annotation.Nonnull String notificationType) {
    this.notificationType = notificationType;
    return this;
  }

  /**
   * The type of the notification
   * @return notificationType
   */
  @javax.annotation.Nonnull
  public String getNotificationType() {
    return notificationType;
  }

  public void setNotificationType(@javax.annotation.Nonnull String notificationType) {
    this.notificationType = notificationType;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CouponsNotificationData couponsNotificationData = (CouponsNotificationData) o;
    return Objects.equals(this.typeOfChange, couponsNotificationData.typeOfChange) &&
        Objects.equals(this.operation, couponsNotificationData.operation) &&
        Objects.equals(this.employeeName, couponsNotificationData.employeeName) &&
        Objects.equals(this.data, couponsNotificationData.data) &&
        Objects.equals(this.totalResultSize, couponsNotificationData.totalResultSize) &&
        Objects.equals(this.notificationType, couponsNotificationData.notificationType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(typeOfChange, operation, employeeName, data, totalResultSize, notificationType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CouponsNotificationData {\n");
    sb.append("    typeOfChange: ").append(toIndentedString(typeOfChange)).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("    employeeName: ").append(toIndentedString(employeeName)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    totalResultSize: ").append(toIndentedString(totalResultSize)).append("\n");
    sb.append("    notificationType: ").append(toIndentedString(notificationType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("TypeOfChange");
    openapiFields.add("Operation");
    openapiFields.add("EmployeeName");
    openapiFields.add("data");
    openapiFields.add("totalResultSize");
    openapiFields.add("NotificationType");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("TypeOfChange");
    openapiRequiredFields.add("Operation");
    openapiRequiredFields.add("EmployeeName");
    openapiRequiredFields.add("NotificationType");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CouponsNotificationData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CouponsNotificationData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CouponsNotificationData is not found in the empty JSON string", CouponsNotificationData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CouponsNotificationData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CouponsNotificationData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CouponsNotificationData.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("TypeOfChange").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `TypeOfChange` to be a primitive type in the JSON string but got `%s`", jsonObj.get("TypeOfChange").toString()));
      }
      if (!jsonObj.get("Operation").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Operation` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Operation").toString()));
      }
      if (!jsonObj.get("EmployeeName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `EmployeeName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("EmployeeName").toString()));
      }
      if (jsonObj.get("data") != null && !jsonObj.get("data").isJsonNull()) {
        JsonArray jsonArraydata = jsonObj.getAsJsonArray("data");
        if (jsonArraydata != null) {
          // ensure the json data is an array
          if (!jsonObj.get("data").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `data` to be an array in the JSON string but got `%s`", jsonObj.get("data").toString()));
          }

          // validate the optional field `data` (array)
          for (int i = 0; i < jsonArraydata.size(); i++) {
            ExtendedCoupon.validateJsonElement(jsonArraydata.get(i));
          };
        }
      }
      if (!jsonObj.get("NotificationType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `NotificationType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("NotificationType").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CouponsNotificationData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CouponsNotificationData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CouponsNotificationData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CouponsNotificationData.class));

       return (TypeAdapter<T>) new TypeAdapter<CouponsNotificationData>() {
           @Override
           public void write(JsonWriter out, CouponsNotificationData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CouponsNotificationData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CouponsNotificationData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CouponsNotificationData
   * @throws IOException if the JSON string is invalid with respect to CouponsNotificationData
   */
  public static CouponsNotificationData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CouponsNotificationData.class);
  }

  /**
   * Convert an instance of CouponsNotificationData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

