/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import one.talon.model.AdditionalCost;
import one.talon.model.CartItem;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import one.talon.JSON;

/**
 * CustomerSessionV2
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class CustomerSessionV2 {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private Long id;

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  @javax.annotation.Nonnull
  private OffsetDateTime created;

  public static final String SERIALIZED_NAME_INTEGRATION_ID = "integrationId";
  @SerializedName(SERIALIZED_NAME_INTEGRATION_ID)
  @javax.annotation.Nonnull
  private String integrationId;

  public static final String SERIALIZED_NAME_APPLICATION_ID = "applicationId";
  @SerializedName(SERIALIZED_NAME_APPLICATION_ID)
  @javax.annotation.Nonnull
  private Long applicationId;

  public static final String SERIALIZED_NAME_PROFILE_ID = "profileId";
  @SerializedName(SERIALIZED_NAME_PROFILE_ID)
  @javax.annotation.Nullable
  private String profileId;

  public static final String SERIALIZED_NAME_STORE_INTEGRATION_ID = "storeIntegrationId";
  @SerializedName(SERIALIZED_NAME_STORE_INTEGRATION_ID)
  @javax.annotation.Nullable
  private String storeIntegrationId;

  public static final String SERIALIZED_NAME_EVALUABLE_CAMPAIGN_IDS = "evaluableCampaignIds";
  @SerializedName(SERIALIZED_NAME_EVALUABLE_CAMPAIGN_IDS)
  @javax.annotation.Nullable
  private List<Long> evaluableCampaignIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_COUPON_CODES = "couponCodes";
  @SerializedName(SERIALIZED_NAME_COUPON_CODES)
  @javax.annotation.Nullable
  private List<String> couponCodes = new ArrayList<>();

  public static final String SERIALIZED_NAME_REFERRAL_CODE = "referralCode";
  @SerializedName(SERIALIZED_NAME_REFERRAL_CODE)
  @javax.annotation.Nullable
  private String referralCode;

  public static final String SERIALIZED_NAME_LOYALTY_CARDS = "loyaltyCards";
  @SerializedName(SERIALIZED_NAME_LOYALTY_CARDS)
  @javax.annotation.Nullable
  private List<String> loyaltyCards = new ArrayList<>();

  /**
   * Indicates the current state of the session. Sessions can be created as &#x60;open&#x60; or &#x60;closed&#x60;. The state transitions are:  1. &#x60;open&#x60; → &#x60;closed&#x60; 2. &#x60;open&#x60; → &#x60;cancelled&#x60; 3. Either:    - &#x60;closed&#x60; → &#x60;cancelled&#x60; (**only** via [Update customer session](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2)) or    - &#x60;closed&#x60; → &#x60;partially_returned&#x60; (**only** via [Return cart items](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/returnCartItems))    - &#x60;closed&#x60; → &#x60;open&#x60; (**only** via [Reopen customer session](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/reopenCustomerSession)) 4. &#x60;partially_returned&#x60; → &#x60;cancelled&#x60;  For more information, see [Customer session states](https://docs.talon.one/docs/dev/concepts/entities/customer-sessions). 
   */
  @JsonAdapter(StateEnum.Adapter.class)
  public enum StateEnum {
    OPEN("open"),
    
    CLOSED("closed"),
    
    PARTIALLY_RETURNED("partially_returned"),
    
    CANCELLED("cancelled");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StateEnum fromValue(String value) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StateEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StateEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StateEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  @javax.annotation.Nullable
  private StateEnum state = StateEnum.OPEN;

  public static final String SERIALIZED_NAME_CART_ITEMS = "cartItems";
  @SerializedName(SERIALIZED_NAME_CART_ITEMS)
  @javax.annotation.Nullable
  private List<CartItem> cartItems = new ArrayList<>();

  public static final String SERIALIZED_NAME_ADDITIONAL_COSTS = "additionalCosts";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_COSTS)
  @javax.annotation.Nullable
  private Map<String, AdditionalCost> additionalCosts = new HashMap<>();

  public static final String SERIALIZED_NAME_IDENTIFIERS = "identifiers";
  @SerializedName(SERIALIZED_NAME_IDENTIFIERS)
  @javax.annotation.Nullable
  private List<String> identifiers = new ArrayList<>();

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  @javax.annotation.Nullable
  private Object attributes;

  public static final String SERIALIZED_NAME_FIRST_SESSION = "firstSession";
  @SerializedName(SERIALIZED_NAME_FIRST_SESSION)
  @javax.annotation.Nonnull
  private Boolean firstSession;

  public static final String SERIALIZED_NAME_UPDATE_COUNT = "updateCount";
  @SerializedName(SERIALIZED_NAME_UPDATE_COUNT)
  @javax.annotation.Nonnull
  private Long updateCount;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  @javax.annotation.Nonnull
  private BigDecimal total;

  public static final String SERIALIZED_NAME_CART_ITEM_TOTAL = "cartItemTotal";
  @SerializedName(SERIALIZED_NAME_CART_ITEM_TOTAL)
  @javax.annotation.Nonnull
  private BigDecimal cartItemTotal;

  public static final String SERIALIZED_NAME_ADDITIONAL_COST_TOTAL = "additionalCostTotal";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_COST_TOTAL)
  @javax.annotation.Nonnull
  private BigDecimal additionalCostTotal;

  public static final String SERIALIZED_NAME_UPDATED = "updated";
  @SerializedName(SERIALIZED_NAME_UPDATED)
  @javax.annotation.Nonnull
  private OffsetDateTime updated;

  public CustomerSessionV2() {
  }

  public CustomerSessionV2 id(@javax.annotation.Nonnull Long id) {
    this.id = id;
    return this;
  }

  /**
   * The internal ID of this entity.
   * @return id
   */
  @javax.annotation.Nonnull
  public Long getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull Long id) {
    this.id = id;
  }


  public CustomerSessionV2 created(@javax.annotation.Nonnull OffsetDateTime created) {
    this.created = created;
    return this;
  }

  /**
   * The time this entity was created.
   * @return created
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(@javax.annotation.Nonnull OffsetDateTime created) {
    this.created = created;
  }


  public CustomerSessionV2 integrationId(@javax.annotation.Nonnull String integrationId) {
    this.integrationId = integrationId;
    return this;
  }

  /**
   * The integration ID set by your integration layer.
   * @return integrationId
   */
  @javax.annotation.Nonnull
  public String getIntegrationId() {
    return integrationId;
  }

  public void setIntegrationId(@javax.annotation.Nonnull String integrationId) {
    this.integrationId = integrationId;
  }


  public CustomerSessionV2 applicationId(@javax.annotation.Nonnull Long applicationId) {
    this.applicationId = applicationId;
    return this;
  }

  /**
   * The ID of the Application that owns this entity.
   * @return applicationId
   */
  @javax.annotation.Nonnull
  public Long getApplicationId() {
    return applicationId;
  }

  public void setApplicationId(@javax.annotation.Nonnull Long applicationId) {
    this.applicationId = applicationId;
  }


  public CustomerSessionV2 profileId(@javax.annotation.Nullable String profileId) {
    this.profileId = profileId;
    return this;
  }

  /**
   * ID of the customer profile set by your integration layer.  **Note:** If the customer does not yet have a known &#x60;profileId&#x60;, we recommend you use a guest &#x60;profileId&#x60;. 
   * @return profileId
   */
  @javax.annotation.Nullable
  public String getProfileId() {
    return profileId;
  }

  public void setProfileId(@javax.annotation.Nullable String profileId) {
    this.profileId = profileId;
  }


  public CustomerSessionV2 storeIntegrationId(@javax.annotation.Nullable String storeIntegrationId) {
    this.storeIntegrationId = storeIntegrationId;
    return this;
  }

  /**
   * The integration ID of the store. You choose this ID when you create a store.
   * @return storeIntegrationId
   */
  @javax.annotation.Nullable
  public String getStoreIntegrationId() {
    return storeIntegrationId;
  }

  public void setStoreIntegrationId(@javax.annotation.Nullable String storeIntegrationId) {
    this.storeIntegrationId = storeIntegrationId;
  }


  public CustomerSessionV2 evaluableCampaignIds(@javax.annotation.Nullable List<Long> evaluableCampaignIds) {
    this.evaluableCampaignIds = evaluableCampaignIds;
    return this;
  }

  public CustomerSessionV2 addEvaluableCampaignIdsItem(Long evaluableCampaignIdsItem) {
    if (this.evaluableCampaignIds == null) {
      this.evaluableCampaignIds = new ArrayList<>();
    }
    this.evaluableCampaignIds.add(evaluableCampaignIdsItem);
    return this;
  }

  /**
   * When using the &#x60;dry&#x60; query parameter, use this property to list the campaign to be evaluated by the Rule Engine.  These campaigns will be evaluated, even if they are disabled, allowing you to test specific campaigns before activating them. 
   * @return evaluableCampaignIds
   */
  @javax.annotation.Nullable
  public List<Long> getEvaluableCampaignIds() {
    return evaluableCampaignIds;
  }

  public void setEvaluableCampaignIds(@javax.annotation.Nullable List<Long> evaluableCampaignIds) {
    this.evaluableCampaignIds = evaluableCampaignIds;
  }


  public CustomerSessionV2 couponCodes(@javax.annotation.Nullable List<String> couponCodes) {
    this.couponCodes = couponCodes;
    return this;
  }

  public CustomerSessionV2 addCouponCodesItem(String couponCodesItem) {
    if (this.couponCodes == null) {
      this.couponCodes = new ArrayList<>();
    }
    this.couponCodes.add(couponCodesItem);
    return this;
  }

  /**
   * Any coupon codes entered.  **Important - for requests only**:  - If you [create a coupon budget](https://docs.talon.one/docs/product/campaigns/settings/managing-campaign-budgets/#budget-types) for your campaign, ensure the session contains a coupon code by the time you close it. - In requests where &#x60;dry&#x3D;false&#x60;, providing an empty array discards any previous coupons. To avoid this, omit the parameter entirely. 
   * @return couponCodes
   */
  @javax.annotation.Nullable
  public List<String> getCouponCodes() {
    return couponCodes;
  }

  public void setCouponCodes(@javax.annotation.Nullable List<String> couponCodes) {
    this.couponCodes = couponCodes;
  }


  public CustomerSessionV2 referralCode(@javax.annotation.Nullable String referralCode) {
    this.referralCode = referralCode;
    return this;
  }

  /**
   * Any referral code entered.  **Important - for requests only**:  - If you [create a referral budget](https://docs.talon.one/docs/product/campaigns/settings/managing-campaign-budgets/#budget-types) for your campaign, ensure the session contains a referral code by the time you close it. - In requests where &#x60;dry&#x3D;false&#x60;, providing an empty value discards the previous referral code. To avoid this, omit the parameter entirely. 
   * @return referralCode
   */
  @javax.annotation.Nullable
  public String getReferralCode() {
    return referralCode;
  }

  public void setReferralCode(@javax.annotation.Nullable String referralCode) {
    this.referralCode = referralCode;
  }


  public CustomerSessionV2 loyaltyCards(@javax.annotation.Nullable List<String> loyaltyCards) {
    this.loyaltyCards = loyaltyCards;
    return this;
  }

  public CustomerSessionV2 addLoyaltyCardsItem(String loyaltyCardsItem) {
    if (this.loyaltyCards == null) {
      this.loyaltyCards = new ArrayList<>();
    }
    this.loyaltyCards.add(loyaltyCardsItem);
    return this;
  }

  /**
   * Identifier of a loyalty card.
   * @return loyaltyCards
   */
  @javax.annotation.Nullable
  public List<String> getLoyaltyCards() {
    return loyaltyCards;
  }

  public void setLoyaltyCards(@javax.annotation.Nullable List<String> loyaltyCards) {
    this.loyaltyCards = loyaltyCards;
  }


  public CustomerSessionV2 state(@javax.annotation.Nullable StateEnum state) {
    this.state = state;
    return this;
  }

  /**
   * Indicates the current state of the session. Sessions can be created as &#x60;open&#x60; or &#x60;closed&#x60;. The state transitions are:  1. &#x60;open&#x60; → &#x60;closed&#x60; 2. &#x60;open&#x60; → &#x60;cancelled&#x60; 3. Either:    - &#x60;closed&#x60; → &#x60;cancelled&#x60; (**only** via [Update customer session](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2)) or    - &#x60;closed&#x60; → &#x60;partially_returned&#x60; (**only** via [Return cart items](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/returnCartItems))    - &#x60;closed&#x60; → &#x60;open&#x60; (**only** via [Reopen customer session](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/reopenCustomerSession)) 4. &#x60;partially_returned&#x60; → &#x60;cancelled&#x60;  For more information, see [Customer session states](https://docs.talon.one/docs/dev/concepts/entities/customer-sessions). 
   * @return state
   */
  @javax.annotation.Nullable
  public StateEnum getState() {
    return state;
  }

  public void setState(@javax.annotation.Nullable StateEnum state) {
    this.state = state;
  }


  public CustomerSessionV2 cartItems(@javax.annotation.Nullable List<CartItem> cartItems) {
    this.cartItems = cartItems;
    return this;
  }

  public CustomerSessionV2 addCartItemsItem(CartItem cartItemsItem) {
    if (this.cartItems == null) {
      this.cartItems = new ArrayList<>();
    }
    this.cartItems.add(cartItemsItem);
    return this;
  }

  /**
   * The items to add to this session. **Do not exceed 1000 items** and ensure the sum of all cart item&#39;s &#x60;quantity&#x60; **does not exceed 10.000** per request. 
   * @return cartItems
   */
  @javax.annotation.Nullable
  public List<CartItem> getCartItems() {
    return cartItems;
  }

  public void setCartItems(@javax.annotation.Nullable List<CartItem> cartItems) {
    this.cartItems = cartItems;
  }


  public CustomerSessionV2 additionalCosts(@javax.annotation.Nullable Map<String, AdditionalCost> additionalCosts) {
    this.additionalCosts = additionalCosts;
    return this;
  }

  public CustomerSessionV2 putAdditionalCostsItem(String key, AdditionalCost additionalCostsItem) {
    if (this.additionalCosts == null) {
      this.additionalCosts = new HashMap<>();
    }
    this.additionalCosts.put(key, additionalCostsItem);
    return this;
  }

  /**
   * Use this property to set a value for the additional costs of this session, such as a shipping cost.  They must be created in the Campaign Manager before you set them with this property. See [Managing additional costs](https://docs.talon.one/docs/product/account/dev-tools/managing-additional-costs). 
   * @return additionalCosts
   */
  @javax.annotation.Nullable
  public Map<String, AdditionalCost> getAdditionalCosts() {
    return additionalCosts;
  }

  public void setAdditionalCosts(@javax.annotation.Nullable Map<String, AdditionalCost> additionalCosts) {
    this.additionalCosts = additionalCosts;
  }


  public CustomerSessionV2 identifiers(@javax.annotation.Nullable List<String> identifiers) {
    this.identifiers = identifiers;
    return this;
  }

  public CustomerSessionV2 addIdentifiersItem(String identifiersItem) {
    if (this.identifiers == null) {
      this.identifiers = new ArrayList<>();
    }
    this.identifiers.add(identifiersItem);
    return this;
  }

  /**
   * Session custom identifiers that you can set limits on or use inside your rules.  For example, you can use IP addresses as identifiers to potentially identify devices and limit discounts abuse in case of customers creating multiple accounts. See the [tutorial](https://docs.talon.one/docs/dev/tutorials/using-identifiers).  **Important**: Ensure the session contains an identifier by the time you close it if: - You [create a unique identifier budget](https://docs.talon.one/docs/product/campaigns/settings/managing-campaign-budgets/#budget-types) for your campaign. - Your campaign has [coupons](https://docs.talon.one/docs/product/campaigns/coupons/coupon-page-overview). - We recommend passing an anonymized (hashed) version of the identifier value. 
   * @return identifiers
   */
  @javax.annotation.Nullable
  public List<String> getIdentifiers() {
    return identifiers;
  }

  public void setIdentifiers(@javax.annotation.Nullable List<String> identifiers) {
    this.identifiers = identifiers;
  }


  public CustomerSessionV2 attributes(@javax.annotation.Nullable Object attributes) {
    this.attributes = attributes;
    return this;
  }

  /**
   * Use this property to set a value for the attributes of your choice. Attributes represent any information to attach to your session, like the shipping city.  You can use [built-in attributes](https://docs.talon.one/docs/dev/concepts/attributes#built-in-attributes) or [custom ones](https://docs.talon.one/docs/dev/concepts/attributes#custom-attributes). Custom attributes must be created in the Campaign Manager before you set them with this property. 
   * @return attributes
   */
  @javax.annotation.Nullable
  public Object getAttributes() {
    return attributes;
  }

  public void setAttributes(@javax.annotation.Nullable Object attributes) {
    this.attributes = attributes;
  }


  public CustomerSessionV2 firstSession(@javax.annotation.Nonnull Boolean firstSession) {
    this.firstSession = firstSession;
    return this;
  }

  /**
   * Indicates whether this is the first session for the customer&#39;s profile. It&#39;s always &#x60;true&#x60; for anonymous sessions.
   * @return firstSession
   */
  @javax.annotation.Nonnull
  public Boolean getFirstSession() {
    return firstSession;
  }

  public void setFirstSession(@javax.annotation.Nonnull Boolean firstSession) {
    this.firstSession = firstSession;
  }


  public CustomerSessionV2 updateCount(@javax.annotation.Nonnull Long updateCount) {
    this.updateCount = updateCount;
    return this;
  }

  /**
   * The number of times the session was updated. When the session is created, this value is initialized to &#x60;1&#x60;.
   * @return updateCount
   */
  @javax.annotation.Nonnull
  public Long getUpdateCount() {
    return updateCount;
  }

  public void setUpdateCount(@javax.annotation.Nonnull Long updateCount) {
    this.updateCount = updateCount;
  }


  public CustomerSessionV2 total(@javax.annotation.Nonnull BigDecimal total) {
    this.total = total;
    return this;
  }

  /**
   * The total value of cart items and additional costs in the session, before any discounts are applied.
   * @return total
   */
  @javax.annotation.Nonnull
  public BigDecimal getTotal() {
    return total;
  }

  public void setTotal(@javax.annotation.Nonnull BigDecimal total) {
    this.total = total;
  }


  public CustomerSessionV2 cartItemTotal(@javax.annotation.Nonnull BigDecimal cartItemTotal) {
    this.cartItemTotal = cartItemTotal;
    return this;
  }

  /**
   * The total value of cart items, before any discounts are applied.
   * @return cartItemTotal
   */
  @javax.annotation.Nonnull
  public BigDecimal getCartItemTotal() {
    return cartItemTotal;
  }

  public void setCartItemTotal(@javax.annotation.Nonnull BigDecimal cartItemTotal) {
    this.cartItemTotal = cartItemTotal;
  }


  public CustomerSessionV2 additionalCostTotal(@javax.annotation.Nonnull BigDecimal additionalCostTotal) {
    this.additionalCostTotal = additionalCostTotal;
    return this;
  }

  /**
   * The total value of additional costs, before any discounts are applied.
   * @return additionalCostTotal
   */
  @javax.annotation.Nonnull
  public BigDecimal getAdditionalCostTotal() {
    return additionalCostTotal;
  }

  public void setAdditionalCostTotal(@javax.annotation.Nonnull BigDecimal additionalCostTotal) {
    this.additionalCostTotal = additionalCostTotal;
  }


  public CustomerSessionV2 updated(@javax.annotation.Nonnull OffsetDateTime updated) {
    this.updated = updated;
    return this;
  }

  /**
   * Timestamp of the most recent event received on this session.
   * @return updated
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getUpdated() {
    return updated;
  }

  public void setUpdated(@javax.annotation.Nonnull OffsetDateTime updated) {
    this.updated = updated;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerSessionV2 customerSessionV2 = (CustomerSessionV2) o;
    return Objects.equals(this.id, customerSessionV2.id) &&
        Objects.equals(this.created, customerSessionV2.created) &&
        Objects.equals(this.integrationId, customerSessionV2.integrationId) &&
        Objects.equals(this.applicationId, customerSessionV2.applicationId) &&
        Objects.equals(this.profileId, customerSessionV2.profileId) &&
        Objects.equals(this.storeIntegrationId, customerSessionV2.storeIntegrationId) &&
        Objects.equals(this.evaluableCampaignIds, customerSessionV2.evaluableCampaignIds) &&
        Objects.equals(this.couponCodes, customerSessionV2.couponCodes) &&
        Objects.equals(this.referralCode, customerSessionV2.referralCode) &&
        Objects.equals(this.loyaltyCards, customerSessionV2.loyaltyCards) &&
        Objects.equals(this.state, customerSessionV2.state) &&
        Objects.equals(this.cartItems, customerSessionV2.cartItems) &&
        Objects.equals(this.additionalCosts, customerSessionV2.additionalCosts) &&
        Objects.equals(this.identifiers, customerSessionV2.identifiers) &&
        Objects.equals(this.attributes, customerSessionV2.attributes) &&
        Objects.equals(this.firstSession, customerSessionV2.firstSession) &&
        Objects.equals(this.updateCount, customerSessionV2.updateCount) &&
        Objects.equals(this.total, customerSessionV2.total) &&
        Objects.equals(this.cartItemTotal, customerSessionV2.cartItemTotal) &&
        Objects.equals(this.additionalCostTotal, customerSessionV2.additionalCostTotal) &&
        Objects.equals(this.updated, customerSessionV2.updated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, created, integrationId, applicationId, profileId, storeIntegrationId, evaluableCampaignIds, couponCodes, referralCode, loyaltyCards, state, cartItems, additionalCosts, identifiers, attributes, firstSession, updateCount, total, cartItemTotal, additionalCostTotal, updated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerSessionV2 {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    integrationId: ").append(toIndentedString(integrationId)).append("\n");
    sb.append("    applicationId: ").append(toIndentedString(applicationId)).append("\n");
    sb.append("    profileId: ").append(toIndentedString(profileId)).append("\n");
    sb.append("    storeIntegrationId: ").append(toIndentedString(storeIntegrationId)).append("\n");
    sb.append("    evaluableCampaignIds: ").append(toIndentedString(evaluableCampaignIds)).append("\n");
    sb.append("    couponCodes: ").append(toIndentedString(couponCodes)).append("\n");
    sb.append("    referralCode: ").append(toIndentedString(referralCode)).append("\n");
    sb.append("    loyaltyCards: ").append(toIndentedString(loyaltyCards)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    cartItems: ").append(toIndentedString(cartItems)).append("\n");
    sb.append("    additionalCosts: ").append(toIndentedString(additionalCosts)).append("\n");
    sb.append("    identifiers: ").append(toIndentedString(identifiers)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    firstSession: ").append(toIndentedString(firstSession)).append("\n");
    sb.append("    updateCount: ").append(toIndentedString(updateCount)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    cartItemTotal: ").append(toIndentedString(cartItemTotal)).append("\n");
    sb.append("    additionalCostTotal: ").append(toIndentedString(additionalCostTotal)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "created", "integrationId", "applicationId", "profileId", "storeIntegrationId", "evaluableCampaignIds", "couponCodes", "referralCode", "loyaltyCards", "state", "cartItems", "additionalCosts", "identifiers", "attributes", "firstSession", "updateCount", "total", "cartItemTotal", "additionalCostTotal", "updated"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "created", "integrationId", "applicationId", "firstSession", "updateCount", "total", "cartItemTotal", "additionalCostTotal", "updated"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CustomerSessionV2
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CustomerSessionV2.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in CustomerSessionV2 is not found in the empty JSON string", CustomerSessionV2.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CustomerSessionV2.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CustomerSessionV2` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CustomerSessionV2.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("integrationId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `integrationId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("integrationId").toString()));
      }
      if ((jsonObj.get("profileId") != null && !jsonObj.get("profileId").isJsonNull()) && !jsonObj.get("profileId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `profileId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("profileId").toString()));
      }
      if ((jsonObj.get("storeIntegrationId") != null && !jsonObj.get("storeIntegrationId").isJsonNull()) && !jsonObj.get("storeIntegrationId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `storeIntegrationId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("storeIntegrationId").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("evaluableCampaignIds") != null && !jsonObj.get("evaluableCampaignIds").isJsonNull() && !jsonObj.get("evaluableCampaignIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `evaluableCampaignIds` to be an array in the JSON string but got `%s`", jsonObj.get("evaluableCampaignIds").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("couponCodes") != null && !jsonObj.get("couponCodes").isJsonNull() && !jsonObj.get("couponCodes").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `couponCodes` to be an array in the JSON string but got `%s`", jsonObj.get("couponCodes").toString()));
      }
      if ((jsonObj.get("referralCode") != null && !jsonObj.get("referralCode").isJsonNull()) && !jsonObj.get("referralCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `referralCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("referralCode").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("loyaltyCards") != null && !jsonObj.get("loyaltyCards").isJsonNull() && !jsonObj.get("loyaltyCards").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `loyaltyCards` to be an array in the JSON string but got `%s`", jsonObj.get("loyaltyCards").toString()));
      }
      if ((jsonObj.get("state") != null && !jsonObj.get("state").isJsonNull()) && !jsonObj.get("state").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `state` to be a primitive type in the JSON string but got `%s`", jsonObj.get("state").toString()));
      }
      // validate the optional field `state`
      if (jsonObj.get("state") != null && !jsonObj.get("state").isJsonNull()) {
        StateEnum.validateJsonElement(jsonObj.get("state"));
      }
      if (jsonObj.get("cartItems") != null && !jsonObj.get("cartItems").isJsonNull()) {
        JsonArray jsonArraycartItems = jsonObj.getAsJsonArray("cartItems");
        if (jsonArraycartItems != null) {
          // ensure the json data is an array
          if (!jsonObj.get("cartItems").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `cartItems` to be an array in the JSON string but got `%s`", jsonObj.get("cartItems").toString()));
          }

          // validate the optional field `cartItems` (array)
          for (int i = 0; i < jsonArraycartItems.size(); i++) {
            CartItem.validateJsonElement(jsonArraycartItems.get(i));
          };
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("identifiers") != null && !jsonObj.get("identifiers").isJsonNull() && !jsonObj.get("identifiers").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `identifiers` to be an array in the JSON string but got `%s`", jsonObj.get("identifiers").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CustomerSessionV2.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CustomerSessionV2' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CustomerSessionV2> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CustomerSessionV2.class));

       return (TypeAdapter<T>) new TypeAdapter<CustomerSessionV2>() {
           @Override
           public void write(JsonWriter out, CustomerSessionV2 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CustomerSessionV2 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CustomerSessionV2 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CustomerSessionV2
   * @throws IOException if the JSON string is invalid with respect to CustomerSessionV2
   */
  public static CustomerSessionV2 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CustomerSessionV2.class);
  }

  /**
   * Convert an instance of CustomerSessionV2 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

