/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import one.talon.JSON;

/**
 * IntegrationEventV2Request
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class IntegrationEventV2Request {
  public static final String SERIALIZED_NAME_PROFILE_ID = "profileId";
  @SerializedName(SERIALIZED_NAME_PROFILE_ID)
  @javax.annotation.Nullable
  private String profileId;

  public static final String SERIALIZED_NAME_STORE_INTEGRATION_ID = "storeIntegrationId";
  @SerializedName(SERIALIZED_NAME_STORE_INTEGRATION_ID)
  @javax.annotation.Nullable
  private String storeIntegrationId;

  public static final String SERIALIZED_NAME_EVALUABLE_CAMPAIGN_IDS = "evaluableCampaignIds";
  @SerializedName(SERIALIZED_NAME_EVALUABLE_CAMPAIGN_IDS)
  @javax.annotation.Nullable
  private List<Long> evaluableCampaignIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private String type;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  @javax.annotation.Nullable
  private Object attributes;

  public static final String SERIALIZED_NAME_LOYALTY_CARDS = "loyaltyCards";
  @SerializedName(SERIALIZED_NAME_LOYALTY_CARDS)
  @javax.annotation.Nullable
  private List<String> loyaltyCards = new ArrayList<>();

  /**
   * Gets or Sets responseContent
   */
  @JsonAdapter(ResponseContentEnum.Adapter.class)
  public enum ResponseContentEnum {
    CUSTOMER_PROFILE("customerProfile"),
    
    TRIGGERED_CAMPAIGNS("triggeredCampaigns"),
    
    LOYALTY("loyalty"),
    
    EVENT("event"),
    
    AWARDED_GIVEAWAYS("awardedGiveaways"),
    
    RULE_FAILURE_REASONS("ruleFailureReasons");

    private String value;

    ResponseContentEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ResponseContentEnum fromValue(String value) {
      for (ResponseContentEnum b : ResponseContentEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ResponseContentEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ResponseContentEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ResponseContentEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ResponseContentEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ResponseContentEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_RESPONSE_CONTENT = "responseContent";
  @SerializedName(SERIALIZED_NAME_RESPONSE_CONTENT)
  @javax.annotation.Nullable
  private List<ResponseContentEnum> responseContent = new ArrayList<>();

  public IntegrationEventV2Request() {
  }

  public IntegrationEventV2Request profileId(@javax.annotation.Nullable String profileId) {
    this.profileId = profileId;
    return this;
  }

  /**
   * ID of the customer profile set by your integration layer.  **Note:** If the customer does not yet have a known &#x60;profileId&#x60;, we recommend you use a guest &#x60;profileId&#x60;. 
   * @return profileId
   */
  @javax.annotation.Nullable
  public String getProfileId() {
    return profileId;
  }

  public void setProfileId(@javax.annotation.Nullable String profileId) {
    this.profileId = profileId;
  }


  public IntegrationEventV2Request storeIntegrationId(@javax.annotation.Nullable String storeIntegrationId) {
    this.storeIntegrationId = storeIntegrationId;
    return this;
  }

  /**
   * The integration ID of the store. You choose this ID when you create a store.
   * @return storeIntegrationId
   */
  @javax.annotation.Nullable
  public String getStoreIntegrationId() {
    return storeIntegrationId;
  }

  public void setStoreIntegrationId(@javax.annotation.Nullable String storeIntegrationId) {
    this.storeIntegrationId = storeIntegrationId;
  }


  public IntegrationEventV2Request evaluableCampaignIds(@javax.annotation.Nullable List<Long> evaluableCampaignIds) {
    this.evaluableCampaignIds = evaluableCampaignIds;
    return this;
  }

  public IntegrationEventV2Request addEvaluableCampaignIdsItem(Long evaluableCampaignIdsItem) {
    if (this.evaluableCampaignIds == null) {
      this.evaluableCampaignIds = new ArrayList<>();
    }
    this.evaluableCampaignIds.add(evaluableCampaignIdsItem);
    return this;
  }

  /**
   * When using the &#x60;dry&#x60; query parameter, use this property to list the campaign to be evaluated by the Rule Engine.  These campaigns will be evaluated, even if they are disabled, allowing you to test specific campaigns before activating them. 
   * @return evaluableCampaignIds
   */
  @javax.annotation.Nullable
  public List<Long> getEvaluableCampaignIds() {
    return evaluableCampaignIds;
  }

  public void setEvaluableCampaignIds(@javax.annotation.Nullable List<Long> evaluableCampaignIds) {
    this.evaluableCampaignIds = evaluableCampaignIds;
  }


  public IntegrationEventV2Request type(@javax.annotation.Nonnull String type) {
    this.type = type;
    return this;
  }

  /**
   * A string representing the event name. Must not be a reserved event name. You create this value when you [create an attribute](https://docs.talon.one/docs/dev/concepts/entities/events#creating-a-custom-event) of type &#x60;event&#x60; in the Campaign Manager. 
   * @return type
   */
  @javax.annotation.Nonnull
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull String type) {
    this.type = type;
  }


  public IntegrationEventV2Request attributes(@javax.annotation.Nullable Object attributes) {
    this.attributes = attributes;
    return this;
  }

  /**
   * Arbitrary additional JSON properties associated with the event. They must be created in the Campaign Manager before setting them with this property. See [creating custom attributes](https://docs.talon.one/docs/product/account/dev-tools/managing-attributes#creating-a-custom-attribute).
   * @return attributes
   */
  @javax.annotation.Nullable
  public Object getAttributes() {
    return attributes;
  }

  public void setAttributes(@javax.annotation.Nullable Object attributes) {
    this.attributes = attributes;
  }


  public IntegrationEventV2Request loyaltyCards(@javax.annotation.Nullable List<String> loyaltyCards) {
    this.loyaltyCards = loyaltyCards;
    return this;
  }

  public IntegrationEventV2Request addLoyaltyCardsItem(String loyaltyCardsItem) {
    if (this.loyaltyCards == null) {
      this.loyaltyCards = new ArrayList<>();
    }
    this.loyaltyCards.add(loyaltyCardsItem);
    return this;
  }

  /**
   * Identifier of the loyalty card used during this event.
   * @return loyaltyCards
   */
  @javax.annotation.Nullable
  public List<String> getLoyaltyCards() {
    return loyaltyCards;
  }

  public void setLoyaltyCards(@javax.annotation.Nullable List<String> loyaltyCards) {
    this.loyaltyCards = loyaltyCards;
  }


  public IntegrationEventV2Request responseContent(@javax.annotation.Nullable List<ResponseContentEnum> responseContent) {
    this.responseContent = responseContent;
    return this;
  }

  public IntegrationEventV2Request addResponseContentItem(ResponseContentEnum responseContentItem) {
    if (this.responseContent == null) {
      this.responseContent = new ArrayList<>();
    }
    this.responseContent.add(responseContentItem);
    return this;
  }

  /**
   * Optional list of requested information to be present on the response related to the tracking custom event. 
   * @return responseContent
   */
  @javax.annotation.Nullable
  public List<ResponseContentEnum> getResponseContent() {
    return responseContent;
  }

  public void setResponseContent(@javax.annotation.Nullable List<ResponseContentEnum> responseContent) {
    this.responseContent = responseContent;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntegrationEventV2Request integrationEventV2Request = (IntegrationEventV2Request) o;
    return Objects.equals(this.profileId, integrationEventV2Request.profileId) &&
        Objects.equals(this.storeIntegrationId, integrationEventV2Request.storeIntegrationId) &&
        Objects.equals(this.evaluableCampaignIds, integrationEventV2Request.evaluableCampaignIds) &&
        Objects.equals(this.type, integrationEventV2Request.type) &&
        Objects.equals(this.attributes, integrationEventV2Request.attributes) &&
        Objects.equals(this.loyaltyCards, integrationEventV2Request.loyaltyCards) &&
        Objects.equals(this.responseContent, integrationEventV2Request.responseContent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(profileId, storeIntegrationId, evaluableCampaignIds, type, attributes, loyaltyCards, responseContent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntegrationEventV2Request {\n");
    sb.append("    profileId: ").append(toIndentedString(profileId)).append("\n");
    sb.append("    storeIntegrationId: ").append(toIndentedString(storeIntegrationId)).append("\n");
    sb.append("    evaluableCampaignIds: ").append(toIndentedString(evaluableCampaignIds)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    loyaltyCards: ").append(toIndentedString(loyaltyCards)).append("\n");
    sb.append("    responseContent: ").append(toIndentedString(responseContent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("profileId", "storeIntegrationId", "evaluableCampaignIds", "type", "attributes", "loyaltyCards", "responseContent"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("type"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to IntegrationEventV2Request
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IntegrationEventV2Request.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in IntegrationEventV2Request is not found in the empty JSON string", IntegrationEventV2Request.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!IntegrationEventV2Request.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `IntegrationEventV2Request` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : IntegrationEventV2Request.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("profileId") != null && !jsonObj.get("profileId").isJsonNull()) && !jsonObj.get("profileId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `profileId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("profileId").toString()));
      }
      if ((jsonObj.get("storeIntegrationId") != null && !jsonObj.get("storeIntegrationId").isJsonNull()) && !jsonObj.get("storeIntegrationId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `storeIntegrationId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("storeIntegrationId").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("evaluableCampaignIds") != null && !jsonObj.get("evaluableCampaignIds").isJsonNull() && !jsonObj.get("evaluableCampaignIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `evaluableCampaignIds` to be an array in the JSON string but got `%s`", jsonObj.get("evaluableCampaignIds").toString()));
      }
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("loyaltyCards") != null && !jsonObj.get("loyaltyCards").isJsonNull() && !jsonObj.get("loyaltyCards").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `loyaltyCards` to be an array in the JSON string but got `%s`", jsonObj.get("loyaltyCards").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("responseContent") != null && !jsonObj.get("responseContent").isJsonNull() && !jsonObj.get("responseContent").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `responseContent` to be an array in the JSON string but got `%s`", jsonObj.get("responseContent").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IntegrationEventV2Request.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IntegrationEventV2Request' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IntegrationEventV2Request> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IntegrationEventV2Request.class));

       return (TypeAdapter<T>) new TypeAdapter<IntegrationEventV2Request>() {
           @Override
           public void write(JsonWriter out, IntegrationEventV2Request value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public IntegrationEventV2Request read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of IntegrationEventV2Request given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of IntegrationEventV2Request
   * @throws IOException if the JSON string is invalid with respect to IntegrationEventV2Request
   */
  public static IntegrationEventV2Request fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IntegrationEventV2Request.class);
  }

  /**
   * Convert an instance of IntegrationEventV2Request to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

