/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import one.talon.JSON;

/**
 * OutgoingIntegrationMoEngagePolicy
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class OutgoingIntegrationMoEngagePolicy {
  public static final String SERIALIZED_NAME_BASE_URL = "baseUrl";
  @SerializedName(SERIALIZED_NAME_BASE_URL)
  @javax.annotation.Nonnull
  private String baseUrl;

  public static final String SERIALIZED_NAME_APP_ID = "appId";
  @SerializedName(SERIALIZED_NAME_APP_ID)
  @javax.annotation.Nonnull
  private String appId;

  public static final String SERIALIZED_NAME_DATA_API_ID = "dataApiId";
  @SerializedName(SERIALIZED_NAME_DATA_API_ID)
  @javax.annotation.Nonnull
  private String dataApiId;

  public static final String SERIALIZED_NAME_DATA_API_KEY = "dataApiKey";
  @SerializedName(SERIALIZED_NAME_DATA_API_KEY)
  @javax.annotation.Nonnull
  private String dataApiKey;

  public OutgoingIntegrationMoEngagePolicy() {
  }

  public OutgoingIntegrationMoEngagePolicy baseUrl(@javax.annotation.Nonnull String baseUrl) {
    this.baseUrl = baseUrl;
    return this;
  }

  /**
   * The base URL of your MoEngage deployment, containing the MoEngage data center number (represented by &#x60;0X&#x60;).
   * @return baseUrl
   */
  @javax.annotation.Nonnull
  public String getBaseUrl() {
    return baseUrl;
  }

  public void setBaseUrl(@javax.annotation.Nonnull String baseUrl) {
    this.baseUrl = baseUrl;
  }


  public OutgoingIntegrationMoEngagePolicy appId(@javax.annotation.Nonnull String appId) {
    this.appId = appId;
    return this;
  }

  /**
   * MoEngage APP ID. See [MoEngage Developer Guide](https://developers.moengage.com/hc/en-us/articles/4404674776724-Overview).
   * @return appId
   */
  @javax.annotation.Nonnull
  public String getAppId() {
    return appId;
  }

  public void setAppId(@javax.annotation.Nonnull String appId) {
    this.appId = appId;
  }


  public OutgoingIntegrationMoEngagePolicy dataApiId(@javax.annotation.Nonnull String dataApiId) {
    this.dataApiId = dataApiId;
    return this;
  }

  /**
   * MoEngage DATA API ID. See [MoEngage Developer Guide](https://developers.moengage.com/hc/en-us/articles/4404674776724-Overview).
   * @return dataApiId
   */
  @javax.annotation.Nonnull
  public String getDataApiId() {
    return dataApiId;
  }

  public void setDataApiId(@javax.annotation.Nonnull String dataApiId) {
    this.dataApiId = dataApiId;
  }


  public OutgoingIntegrationMoEngagePolicy dataApiKey(@javax.annotation.Nonnull String dataApiKey) {
    this.dataApiKey = dataApiKey;
    return this;
  }

  /**
   * MoEngage DATA API Key. See [MoEngage Developer Guide](https://developers.moengage.com/hc/en-us/articles/4404674776724-Overview).
   * @return dataApiKey
   */
  @javax.annotation.Nonnull
  public String getDataApiKey() {
    return dataApiKey;
  }

  public void setDataApiKey(@javax.annotation.Nonnull String dataApiKey) {
    this.dataApiKey = dataApiKey;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutgoingIntegrationMoEngagePolicy outgoingIntegrationMoEngagePolicy = (OutgoingIntegrationMoEngagePolicy) o;
    return Objects.equals(this.baseUrl, outgoingIntegrationMoEngagePolicy.baseUrl) &&
        Objects.equals(this.appId, outgoingIntegrationMoEngagePolicy.appId) &&
        Objects.equals(this.dataApiId, outgoingIntegrationMoEngagePolicy.dataApiId) &&
        Objects.equals(this.dataApiKey, outgoingIntegrationMoEngagePolicy.dataApiKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(baseUrl, appId, dataApiId, dataApiKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutgoingIntegrationMoEngagePolicy {\n");
    sb.append("    baseUrl: ").append(toIndentedString(baseUrl)).append("\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    dataApiId: ").append(toIndentedString(dataApiId)).append("\n");
    sb.append("    dataApiKey: ").append(toIndentedString(dataApiKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("baseUrl", "appId", "dataApiId", "dataApiKey"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("baseUrl", "appId", "dataApiId", "dataApiKey"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OutgoingIntegrationMoEngagePolicy
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OutgoingIntegrationMoEngagePolicy.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in OutgoingIntegrationMoEngagePolicy is not found in the empty JSON string", OutgoingIntegrationMoEngagePolicy.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OutgoingIntegrationMoEngagePolicy.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `OutgoingIntegrationMoEngagePolicy` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : OutgoingIntegrationMoEngagePolicy.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("baseUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `baseUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("baseUrl").toString()));
      }
      if (!jsonObj.get("appId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `appId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("appId").toString()));
      }
      if (!jsonObj.get("dataApiId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `dataApiId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dataApiId").toString()));
      }
      if (!jsonObj.get("dataApiKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `dataApiKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dataApiKey").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OutgoingIntegrationMoEngagePolicy.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OutgoingIntegrationMoEngagePolicy' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OutgoingIntegrationMoEngagePolicy> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OutgoingIntegrationMoEngagePolicy.class));

       return (TypeAdapter<T>) new TypeAdapter<OutgoingIntegrationMoEngagePolicy>() {
           @Override
           public void write(JsonWriter out, OutgoingIntegrationMoEngagePolicy value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OutgoingIntegrationMoEngagePolicy read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OutgoingIntegrationMoEngagePolicy given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OutgoingIntegrationMoEngagePolicy
   * @throws IOException if the JSON string is invalid with respect to OutgoingIntegrationMoEngagePolicy
   */
  public static OutgoingIntegrationMoEngagePolicy fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OutgoingIntegrationMoEngagePolicy.class);
  }

  /**
   * Convert an instance of OutgoingIntegrationMoEngagePolicy to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

