/*
 * Talon.One API
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package one.talon.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import one.talon.JSON;

/**
 * Details about why a rule failed.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class RuleFailureReason {
  public static final String SERIALIZED_NAME_CAMPAIGN_I_D = "campaignID";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN_I_D)
  @javax.annotation.Nonnull
  private Long campaignID;

  public static final String SERIALIZED_NAME_CAMPAIGN_NAME = "campaignName";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN_NAME)
  @javax.annotation.Nonnull
  private String campaignName;

  public static final String SERIALIZED_NAME_RULESET_I_D = "rulesetID";
  @SerializedName(SERIALIZED_NAME_RULESET_I_D)
  @javax.annotation.Nonnull
  private Long rulesetID;

  public static final String SERIALIZED_NAME_COUPON_I_D = "couponID";
  @SerializedName(SERIALIZED_NAME_COUPON_I_D)
  @javax.annotation.Nullable
  private Long couponID;

  public static final String SERIALIZED_NAME_COUPON_VALUE = "couponValue";
  @SerializedName(SERIALIZED_NAME_COUPON_VALUE)
  @javax.annotation.Nullable
  private String couponValue;

  public static final String SERIALIZED_NAME_REFERRAL_I_D = "referralID";
  @SerializedName(SERIALIZED_NAME_REFERRAL_I_D)
  @javax.annotation.Nullable
  private Long referralID;

  public static final String SERIALIZED_NAME_REFERRAL_VALUE = "referralValue";
  @SerializedName(SERIALIZED_NAME_REFERRAL_VALUE)
  @javax.annotation.Nullable
  private String referralValue;

  public static final String SERIALIZED_NAME_RULE_INDEX = "ruleIndex";
  @SerializedName(SERIALIZED_NAME_RULE_INDEX)
  @javax.annotation.Nonnull
  private Long ruleIndex;

  public static final String SERIALIZED_NAME_RULE_NAME = "ruleName";
  @SerializedName(SERIALIZED_NAME_RULE_NAME)
  @javax.annotation.Nonnull
  private String ruleName;

  public static final String SERIALIZED_NAME_CONDITION_INDEX = "conditionIndex";
  @SerializedName(SERIALIZED_NAME_CONDITION_INDEX)
  @javax.annotation.Nullable
  private Long conditionIndex;

  public static final String SERIALIZED_NAME_EFFECT_INDEX = "effectIndex";
  @SerializedName(SERIALIZED_NAME_EFFECT_INDEX)
  @javax.annotation.Nullable
  private Long effectIndex;

  public static final String SERIALIZED_NAME_DETAILS = "details";
  @SerializedName(SERIALIZED_NAME_DETAILS)
  @javax.annotation.Nullable
  private String details;

  public static final String SERIALIZED_NAME_EVALUATION_GROUP_I_D = "evaluationGroupID";
  @SerializedName(SERIALIZED_NAME_EVALUATION_GROUP_I_D)
  @javax.annotation.Nullable
  private Long evaluationGroupID;

  public static final String SERIALIZED_NAME_EVALUATION_GROUP_MODE = "evaluationGroupMode";
  @SerializedName(SERIALIZED_NAME_EVALUATION_GROUP_MODE)
  @javax.annotation.Nullable
  private String evaluationGroupMode;

  public RuleFailureReason() {
  }

  public RuleFailureReason campaignID(@javax.annotation.Nonnull Long campaignID) {
    this.campaignID = campaignID;
    return this;
  }

  /**
   * The ID of the campaign that contains the rule that failed.
   * @return campaignID
   */
  @javax.annotation.Nonnull
  public Long getCampaignID() {
    return campaignID;
  }

  public void setCampaignID(@javax.annotation.Nonnull Long campaignID) {
    this.campaignID = campaignID;
  }


  public RuleFailureReason campaignName(@javax.annotation.Nonnull String campaignName) {
    this.campaignName = campaignName;
    return this;
  }

  /**
   * The name of the campaign that contains the rule that failed.
   * @return campaignName
   */
  @javax.annotation.Nonnull
  public String getCampaignName() {
    return campaignName;
  }

  public void setCampaignName(@javax.annotation.Nonnull String campaignName) {
    this.campaignName = campaignName;
  }


  public RuleFailureReason rulesetID(@javax.annotation.Nonnull Long rulesetID) {
    this.rulesetID = rulesetID;
    return this;
  }

  /**
   * The ID of the ruleset that contains the rule that failed.
   * @return rulesetID
   */
  @javax.annotation.Nonnull
  public Long getRulesetID() {
    return rulesetID;
  }

  public void setRulesetID(@javax.annotation.Nonnull Long rulesetID) {
    this.rulesetID = rulesetID;
  }


  public RuleFailureReason couponID(@javax.annotation.Nullable Long couponID) {
    this.couponID = couponID;
    return this;
  }

  /**
   * The ID of the coupon that was being evaluated at the time of the rule failure.
   * @return couponID
   */
  @javax.annotation.Nullable
  public Long getCouponID() {
    return couponID;
  }

  public void setCouponID(@javax.annotation.Nullable Long couponID) {
    this.couponID = couponID;
  }


  public RuleFailureReason couponValue(@javax.annotation.Nullable String couponValue) {
    this.couponValue = couponValue;
    return this;
  }

  /**
   * The code of the coupon that was being evaluated at the time of the rule failure.
   * @return couponValue
   */
  @javax.annotation.Nullable
  public String getCouponValue() {
    return couponValue;
  }

  public void setCouponValue(@javax.annotation.Nullable String couponValue) {
    this.couponValue = couponValue;
  }


  public RuleFailureReason referralID(@javax.annotation.Nullable Long referralID) {
    this.referralID = referralID;
    return this;
  }

  /**
   * The ID of the referral that was being evaluated at the time of the rule failure.
   * @return referralID
   */
  @javax.annotation.Nullable
  public Long getReferralID() {
    return referralID;
  }

  public void setReferralID(@javax.annotation.Nullable Long referralID) {
    this.referralID = referralID;
  }


  public RuleFailureReason referralValue(@javax.annotation.Nullable String referralValue) {
    this.referralValue = referralValue;
    return this;
  }

  /**
   * The code of the referral that was being evaluated at the time of the rule failure.
   * @return referralValue
   */
  @javax.annotation.Nullable
  public String getReferralValue() {
    return referralValue;
  }

  public void setReferralValue(@javax.annotation.Nullable String referralValue) {
    this.referralValue = referralValue;
  }


  public RuleFailureReason ruleIndex(@javax.annotation.Nonnull Long ruleIndex) {
    this.ruleIndex = ruleIndex;
    return this;
  }

  /**
   * The index of the rule that failed within the ruleset.
   * @return ruleIndex
   */
  @javax.annotation.Nonnull
  public Long getRuleIndex() {
    return ruleIndex;
  }

  public void setRuleIndex(@javax.annotation.Nonnull Long ruleIndex) {
    this.ruleIndex = ruleIndex;
  }


  public RuleFailureReason ruleName(@javax.annotation.Nonnull String ruleName) {
    this.ruleName = ruleName;
    return this;
  }

  /**
   * The name of the rule that failed within the ruleset.
   * @return ruleName
   */
  @javax.annotation.Nonnull
  public String getRuleName() {
    return ruleName;
  }

  public void setRuleName(@javax.annotation.Nonnull String ruleName) {
    this.ruleName = ruleName;
  }


  public RuleFailureReason conditionIndex(@javax.annotation.Nullable Long conditionIndex) {
    this.conditionIndex = conditionIndex;
    return this;
  }

  /**
   * The index of the condition that failed.
   * @return conditionIndex
   */
  @javax.annotation.Nullable
  public Long getConditionIndex() {
    return conditionIndex;
  }

  public void setConditionIndex(@javax.annotation.Nullable Long conditionIndex) {
    this.conditionIndex = conditionIndex;
  }


  public RuleFailureReason effectIndex(@javax.annotation.Nullable Long effectIndex) {
    this.effectIndex = effectIndex;
    return this;
  }

  /**
   * The index of the effect that failed.
   * @return effectIndex
   */
  @javax.annotation.Nullable
  public Long getEffectIndex() {
    return effectIndex;
  }

  public void setEffectIndex(@javax.annotation.Nullable Long effectIndex) {
    this.effectIndex = effectIndex;
  }


  public RuleFailureReason details(@javax.annotation.Nullable String details) {
    this.details = details;
    return this;
  }

  /**
   * More details about the failure.
   * @return details
   */
  @javax.annotation.Nullable
  public String getDetails() {
    return details;
  }

  public void setDetails(@javax.annotation.Nullable String details) {
    this.details = details;
  }


  public RuleFailureReason evaluationGroupID(@javax.annotation.Nullable Long evaluationGroupID) {
    this.evaluationGroupID = evaluationGroupID;
    return this;
  }

  /**
   * The ID of the evaluation group. For more information, see [Managing campaign evaluation](https://docs.talon.one/docs/product/applications/managing-campaign-evaluation).
   * @return evaluationGroupID
   */
  @javax.annotation.Nullable
  public Long getEvaluationGroupID() {
    return evaluationGroupID;
  }

  public void setEvaluationGroupID(@javax.annotation.Nullable Long evaluationGroupID) {
    this.evaluationGroupID = evaluationGroupID;
  }


  public RuleFailureReason evaluationGroupMode(@javax.annotation.Nullable String evaluationGroupMode) {
    this.evaluationGroupMode = evaluationGroupMode;
    return this;
  }

  /**
   * The evaluation mode of the evaluation group. For more information, see [Managing campaign evaluation](https://docs.talon.one/docs/product/applications/managing-campaign-
   * @return evaluationGroupMode
   */
  @javax.annotation.Nullable
  public String getEvaluationGroupMode() {
    return evaluationGroupMode;
  }

  public void setEvaluationGroupMode(@javax.annotation.Nullable String evaluationGroupMode) {
    this.evaluationGroupMode = evaluationGroupMode;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the RuleFailureReason instance itself
   */
  public RuleFailureReason putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RuleFailureReason ruleFailureReason = (RuleFailureReason) o;
    return Objects.equals(this.campaignID, ruleFailureReason.campaignID) &&
        Objects.equals(this.campaignName, ruleFailureReason.campaignName) &&
        Objects.equals(this.rulesetID, ruleFailureReason.rulesetID) &&
        Objects.equals(this.couponID, ruleFailureReason.couponID) &&
        Objects.equals(this.couponValue, ruleFailureReason.couponValue) &&
        Objects.equals(this.referralID, ruleFailureReason.referralID) &&
        Objects.equals(this.referralValue, ruleFailureReason.referralValue) &&
        Objects.equals(this.ruleIndex, ruleFailureReason.ruleIndex) &&
        Objects.equals(this.ruleName, ruleFailureReason.ruleName) &&
        Objects.equals(this.conditionIndex, ruleFailureReason.conditionIndex) &&
        Objects.equals(this.effectIndex, ruleFailureReason.effectIndex) &&
        Objects.equals(this.details, ruleFailureReason.details) &&
        Objects.equals(this.evaluationGroupID, ruleFailureReason.evaluationGroupID) &&
        Objects.equals(this.evaluationGroupMode, ruleFailureReason.evaluationGroupMode)&&
        Objects.equals(this.additionalProperties, ruleFailureReason.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(campaignID, campaignName, rulesetID, couponID, couponValue, referralID, referralValue, ruleIndex, ruleName, conditionIndex, effectIndex, details, evaluationGroupID, evaluationGroupMode, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RuleFailureReason {\n");
    sb.append("    campaignID: ").append(toIndentedString(campaignID)).append("\n");
    sb.append("    campaignName: ").append(toIndentedString(campaignName)).append("\n");
    sb.append("    rulesetID: ").append(toIndentedString(rulesetID)).append("\n");
    sb.append("    couponID: ").append(toIndentedString(couponID)).append("\n");
    sb.append("    couponValue: ").append(toIndentedString(couponValue)).append("\n");
    sb.append("    referralID: ").append(toIndentedString(referralID)).append("\n");
    sb.append("    referralValue: ").append(toIndentedString(referralValue)).append("\n");
    sb.append("    ruleIndex: ").append(toIndentedString(ruleIndex)).append("\n");
    sb.append("    ruleName: ").append(toIndentedString(ruleName)).append("\n");
    sb.append("    conditionIndex: ").append(toIndentedString(conditionIndex)).append("\n");
    sb.append("    effectIndex: ").append(toIndentedString(effectIndex)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    evaluationGroupID: ").append(toIndentedString(evaluationGroupID)).append("\n");
    sb.append("    evaluationGroupMode: ").append(toIndentedString(evaluationGroupMode)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("campaignID", "campaignName", "rulesetID", "couponID", "couponValue", "referralID", "referralValue", "ruleIndex", "ruleName", "conditionIndex", "effectIndex", "details", "evaluationGroupID", "evaluationGroupMode"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("campaignID", "campaignName", "rulesetID", "ruleIndex", "ruleName"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RuleFailureReason
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RuleFailureReason.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in RuleFailureReason is not found in the empty JSON string", RuleFailureReason.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RuleFailureReason.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("campaignName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `campaignName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("campaignName").toString()));
      }
      if ((jsonObj.get("couponValue") != null && !jsonObj.get("couponValue").isJsonNull()) && !jsonObj.get("couponValue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `couponValue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("couponValue").toString()));
      }
      if ((jsonObj.get("referralValue") != null && !jsonObj.get("referralValue").isJsonNull()) && !jsonObj.get("referralValue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `referralValue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("referralValue").toString()));
      }
      if (!jsonObj.get("ruleName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ruleName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ruleName").toString()));
      }
      if ((jsonObj.get("details") != null && !jsonObj.get("details").isJsonNull()) && !jsonObj.get("details").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `details` to be a primitive type in the JSON string but got `%s`", jsonObj.get("details").toString()));
      }
      if ((jsonObj.get("evaluationGroupMode") != null && !jsonObj.get("evaluationGroupMode").isJsonNull()) && !jsonObj.get("evaluationGroupMode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `evaluationGroupMode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("evaluationGroupMode").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RuleFailureReason.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RuleFailureReason' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RuleFailureReason> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RuleFailureReason.class));

       return (TypeAdapter<T>) new TypeAdapter<RuleFailureReason>() {
           @Override
           public void write(JsonWriter out, RuleFailureReason value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public RuleFailureReason read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             RuleFailureReason instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RuleFailureReason given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RuleFailureReason
   * @throws IOException if the JSON string is invalid with respect to RuleFailureReason
   */
  public static RuleFailureReason fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RuleFailureReason.class);
  }

  /**
   * Convert an instance of RuleFailureReason to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

